PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'clan_battle_recommend_data' ('level_id' INTEGER NOT NULL, 'recommend_group' INTEGER NOT NULL, 'level_from' INTEGER NOT NULL, 'level_to' INTEGER NOT NULL, 'atack_party_count' INTEGER NOT NULL, 'magic_party_count' INTEGER NOT NULL, PRIMARY KEY('level_id'));
INSERT INTO clan_battle_recommend_data VALUES(1,1,10,60,2,2);
INSERT INTO clan_battle_recommend_data VALUES(2,1,61,80,2,2);
INSERT INTO clan_battle_recommend_data VALUES(3,1,81,100,2,2);
INSERT INTO clan_battle_recommend_data VALUES(4,2,101,120,2,2);
INSERT INTO clan_battle_recommend_data VALUES(5,2,121,140,2,2);
INSERT INTO clan_battle_recommend_data VALUES(6,2,141,160,2,2);
INSERT INTO clan_battle_recommend_data VALUES(7,3,196,215,2,2);
INSERT INTO clan_battle_recommend_data VALUES(8,3,216,225,2,2);
INSERT INTO clan_battle_recommend_data VALUES(9,3,226,235,2,2);
CREATE INDEX 'clan_battle_recommend_data_0_recommend_group' on 'clan_battle_recommend_data'('recommend_group');
COMMIT;
