PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'custom_mypage_group' ('group_id' INTEGER NOT NULL, 'group_name' TEXT NOT NULL, PRIMARY KEY('group_id'));
INSERT INTO custom_mypage_group VALUES(10001,'公主连结！Re:Dive 1');
INSERT INTO custom_mypage_group VALUES(10002,'公主连结！Re:Dive 2');
INSERT INTO custom_mypage_group VALUES(10003,'公主连结！Re:Dive 3');
INSERT INTO custom_mypage_group VALUES(10004,'公主连结！Re:Dive 4');
INSERT INTO custom_mypage_group VALUES(10005,'公主连结！Re:Dive 第2季 1');
INSERT INTO custom_mypage_group VALUES(10006,'公主连结！Re:Dive 第2季 2');
INSERT INTO custom_mypage_group VALUES(10007,'公主连结！Re:Dive 第2季 3');
INSERT INTO custom_mypage_group VALUES(10008,'公主连结！Re:Dive 第2季 全卷购买特典');
INSERT INTO custom_mypage_group VALUES(20001,'公主连结！Re:Dive 3周年纪念');
INSERT INTO custom_mypage_group VALUES(20002,'官方插画 第3卷 发售纪念道具');
INSERT INTO custom_mypage_group VALUES(20003,'公主连结！Re:Dive 3.5周年纪念');
INSERT INTO custom_mypage_group VALUES(20004,'公主连结！Re:Dive 4周年纪念');
INSERT INTO custom_mypage_group VALUES(30001,'小游戏');
INSERT INTO custom_mypage_group VALUES(40001,'大家的日历');
COMMIT;
