PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'fke_happening_list' ('happening_id' INTEGER NOT NULL, 'happening_name' TEXT NOT NULL, PRIMARY KEY('happening_id'));
INSERT INTO fke_happening_list VALUES(1,'梦魇牡羊');
INSERT INTO fke_happening_list VALUES(2,'香蕉皮跳跃');
INSERT INTO fke_happening_list VALUES(3,'香蕉皮滑行');
INSERT INTO fke_happening_list VALUES(4,'步美的团扇');
INSERT INTO fke_happening_list VALUES(5,'恶霸官爷雕像');
INSERT INTO fke_happening_list VALUES(6,'间歇泉');
INSERT INTO fke_happening_list VALUES(7,'龙卷风');
INSERT INTO fke_happening_list VALUES(8,'逆风');
INSERT INTO fke_happening_list VALUES(9,'骤雨');
INSERT INTO fke_happening_list VALUES(10,'基兹');
INSERT INTO fke_happening_list VALUES(11,'落雷');
INSERT INTO fke_happening_list VALUES(12,'弹球');
INSERT INTO fke_happening_list VALUES(13,'超低空飞行');
INSERT INTO fke_happening_list VALUES(14,'冲入平流层');
INSERT INTO fke_happening_list VALUES(15,'火箭');
INSERT INTO fke_happening_list VALUES(16,'妮侬的爆裂忍术');
INSERT INTO fke_happening_list VALUES(17,'腹部滑行');
INSERT INTO fke_happening_list VALUES(18,'顺风');
INSERT INTO fke_happening_list VALUES(19,'钻头');
INSERT INTO fke_happening_list VALUES(20,'头晕目眩');
COMMIT;
