PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'hatsune_description' ('id' INTEGER NOT NULL, 'event_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO hatsune_description VALUES(1,10001,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(2,10001,1,'随着活动关卡通关，会有BOSS登场。\n使用BOSS券就可以挑战BOSS。\n击败BOSS就可以获得大量讨伐证，请尽情挑战吧。');
INSERT INTO hatsune_description VALUES(3,10001,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(4,10002,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(5,10002,1,'随着活动关卡通关，会有BOSS登场。\n使用BOSS券就可以挑战BOSS。\n击败BOSS就可以获得大量讨伐证，请尽情挑战吧。');
INSERT INTO hatsune_description VALUES(6,10002,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(7,10003,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(8,10003,1,'随着活动关卡通关，会有BOSS登场。\n使用BOSS券就可以挑战BOSS。\n击败BOSS就可以获得大量讨伐证，请尽情挑战吧。');
INSERT INTO hatsune_description VALUES(9,10003,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(10,10004,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(11,10004,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(12,10004,1,'强力的BOSS（VERY HARD）会登场。\nVERY HARD难度BOSS1天可以讨伐1只。\n做好充分的准备，认真迎接挑战吧。');
INSERT INTO hatsune_description VALUES(13,10004,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(14,10005,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(15,10005,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(16,10005,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(17,10005,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(18,10006,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(19,10006,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(20,10006,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(21,10007,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(22,10007,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(23,10007,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(24,10007,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(25,10008,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(26,10008,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(27,10008,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(28,10009,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(29,10009,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(30,10009,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(31,10009,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(32,10010,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(33,10010,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(34,10010,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(35,10010,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(36,10010,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加豪华的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(37,10011,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(38,10011,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(39,10011,1,'在VERY HARD难度中，会有强力的BOSS出现。\n1天可以讨伐1只VERY HARD难度BOSS。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(40,10011,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(41,10011,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加豪华的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(42,10012,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(43,10012,1,'在VERY HARD难度中，会有强力的BOSS出现。\nVERY HARD难度BOSS1天可以讨伐1只。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(44,10012,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(45,10012,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加豪华的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(46,10013,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(47,10013,1,'完成活动限定的任务后，会有\n解锁角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(48,10013,1,'在VERY HARD难度中，会有强力的BOSS出现。\nVERY HARD难度BOSS1天可以讨伐1只。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(49,10013,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(50,10013,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加豪华的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(51,10014,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(52,10014,1,'随着活动关卡通关，会有BOSS登场。\n使用BOSS券就可以挑战BOSS。\n击败BOSS就可以获得大量讨伐证，请尽情挑战吧。');
INSERT INTO hatsune_description VALUES(53,10014,1,'在VERY HARD难度中，会有强力的BOSS出现。\nVERY HARD难度BOSS1天可以讨伐1只。\n请做好充足的准备，全神贯注迎接挑战吧。');
INSERT INTO hatsune_description VALUES(54,10014,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(55,10015,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(56,10015,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(57,10015,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(58,10015,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(59,10016,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(60,10016,1,'随着活动关卡通关，会有BOSS登场。\n使用BOSS券就可以挑战BOSS。\n击败BOSS就可以获得大量讨伐证，请尽情挑战吧。');
INSERT INTO hatsune_description VALUES(61,10016,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(62,10016,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(63,10017,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(64,10017,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(65,10017,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(66,10017,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(67,10017,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(68,10017,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(69,10017,4,'挑战活动关卡和BOSS时，会触发信赖度章节。根据对话的结果，能提升信赖度，　　　　　　当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(70,10018,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(71,10018,1,'随着活动关卡通关，会有BOSS登场。\n使用BOSS券就可以挑战BOSS。\n击败BOSS就可以获得大量讨伐证，请尽情挑战吧。');
INSERT INTO hatsune_description VALUES(72,10018,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(73,10018,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1001901,10019,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1001902,10019,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1001903,10019,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1001904,10019,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1001905,10019,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1001906,10019,4,'挑战活动关卡和BOSS时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(1002001,10020,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002002,10020,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1002003,10020,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002004,10020,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002201,10022,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002202,10022,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1002203,10022,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002204,10022,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002301,10023,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002302,10023,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002303,10023,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002304,10023,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1002305,10023,4,'挑战活动关卡和BOSS时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(1002306,10023,5,'碧结束了在圣特蕾莎女子学院的短暂插班学习后，\n收到了来自『和睦部』\n那3人的信件……');
INSERT INTO hatsune_description VALUES(1002401,10024,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002402,10024,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002403,10024,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002501,10025,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002502,10025,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1002503,10025,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002504,10025,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002505,10025,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1002506,10025,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(1002507,10025,4,'挑战活动关卡和BOSS时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(1002601,10026,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002602,10026,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1002603,10026,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002604,10026,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002701,10027,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002702,10027,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002703,10027,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002704,10027,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1002705,10027,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(1002706,10027,4,'挑战活动关卡和BOSS时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(1002801,10028,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002802,10028,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002803,10028,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002901,10029,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1002902,10029,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1002903,10029,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1002904,10029,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1002905,10029,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1002906,10029,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(1002907,10029,4,'挑战活动关卡和BOSS时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(1003001,10030,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1003002,10030,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1003003,10030,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1003004,10030,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1003101,10031,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1003102,10031,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1003103,10031,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1003104,10031,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1003105,10031,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1003106,10031,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(1003201,10032,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1003202,10032,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1003203,10032,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1003204,10032,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1003301,10033,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1003302,10033,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1003303,10033,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1003304,10033,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1003305,10033,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。\n活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1003306,10033,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(1003307,10033,4,'挑战活动关卡和BOSS时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO hatsune_description VALUES(1003401,10034,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(1003402,10034,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(1003403,10034,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(1003404,10034,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(1003405,10034,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1003406,10034,3,'在Exhibition模式下可以多次挑战SPECIAL BOSS。\n此外，也可以保存战斗记录来进行回顾，\n请寻找适合自己的攻略方法，尝试各种各样的编组吧。');
INSERT INTO hatsune_description VALUES(100210105,10021,1,'在活动中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO hatsune_description VALUES(100210106,10021,1,'完成活动限定的任务后，会有\n可解锁的角色登场。请在活动期间\n努力完成任务吧。');
INSERT INTO hatsune_description VALUES(100210107,10021,1,'在VERY HARD难度中，还会出现强大的BOSS。\n「VERY HARD」BOSS，1天只可以讨伐1只。\n请在做好了充足的准备后，再去挑战吧。');
INSERT INTO hatsune_description VALUES(100210108,10021,1,'讨伐证可以用来兑换报酬。\n报酬也包括在活动中登场的部分角色的记忆碎片。\n收集记忆碎片将角色变为自己的同伴吧。');
INSERT INTO hatsune_description VALUES(100210309,10021,3,'特别关卡是战斗模式会发生3个阶段式变化的关卡。\n在这里获得更加丰厚的报酬和任务报酬吧。活动期间只能讨伐1只，所以，请好好研究编组进行挑战。');
INSERT INTO hatsune_description VALUES(1000802001,10008,2,'为了寻找工作，杏奈前往了溪谷的洞窟。\n为了寻找古文书，七七香向着书商的货源渠道进发了。\n而流夏则接受了村民的委托，前往了村子。\n3个人分别为了自己的目的而朝着目的地出发了。');
INSERT INTO hatsune_description VALUES(1000802002,10008,2,'流夏将村子里的恶霸狠狠地收拾了一顿。\n和担心被报复的村民对话时，\n她意识到了一件事，在溪谷一带还存在着暗地中活跃的地方一霸。\n而另一边，前往溪谷洞窟的杏奈……');
INSERT INTO hatsune_description VALUES(1000802003,10008,2,'杏奈一行本打算在溪谷的洞窟里开始工作，\n却发现那里和事先听说的情况不同，到处都是无视法律的家伙，\n环境十分恶劣，还受监工压榨。\n与此同时，前往进货渠道的七七香则……');
INSERT INTO hatsune_description VALUES(1000802004,10008,2,'被某位贵族强行独占了古文书后，\n七七香并没能完成自己进货的目的。\n在返回路上被恶霸袭击的她，\n为了与流夏汇合而急急忙忙地踏上了前往村子的道路……');
INSERT INTO hatsune_description VALUES(1000802005,10008,2,'得知了溪谷的洞窟就是恶霸们的大本营，\n流夏和七七香决定和杏奈她们汇合。\n救出了好不容易才逃出来的杏奈一行人，\n大家决定先从洞窟里逃出去。');
INSERT INTO hatsune_description VALUES(1001002001,10010,2,'这是献上祈愿并将其净化的神殿。在此处，\n未能得偿所愿的「实体化的愿望」会袭击人类，\n因此，优衣等人接到了警卫工作的委托。\n一行人为了得到报酬发红包而接下了这份工作。');
INSERT INTO hatsune_description VALUES(1001002002,10010,2,'尽管因为招呼参拜的客人而忙得晕头转向，\n但大家还是互相帮助，将工作进行了下去。\n就在这时，出现了一只想要寻找父母的「实体化的愿望」，\n最终因日和莉等人以父母般的温柔相待而得到了净化。');
INSERT INTO hatsune_description VALUES(1001002003,10010,2,'大家渐渐适应了这份工作，这时，冒出了一只\n想要知道如何跟女朋友接吻的「实体化的愿望」。\n主人公在保护身体不适的优衣时差点亲上她，\n愿望因目睹这一幕而得到了净化。');
INSERT INTO hatsune_description VALUES(1001002004,10010,2,'夜幕降临，参拜的客人也随之增多，一行人变得更加忙碌起来。\n就在这时，「实体化的愿望」出现了。\n它彷徨哀叹着希望有人来帮助自己打起精神，\n怜的「拼命」应援让它得到了净化。');
INSERT INTO hatsune_description VALUES(1001002005,10010,2,'在净化了一个又一个愿望之后，大家得到了一段休息的时光。\n年末即将来临，这是愿望变得最为强烈的几个小时，\n「实体化的愿望」接踵而至，\n失控的愿望变成了黑色的雾气，笼罩了整座神殿。');
INSERT INTO hatsune_description VALUES(1001702001,10017,2,'【美食殿堂】等人被自称培提尔其乌斯的男人所袭击。\n爱蜜莉雅她们在千钧一发之际击退了身为魔女教大罪司教的他，\n与【美食殿堂】的各位加深了感情后\n暂时借住在【咲恋救济院】。');
INSERT INTO hatsune_description VALUES(1001702002,10017,2,'大罪司教培提尔其乌斯暗中的活动惊动了王宫骑士团，\n因此，副团长克莉丝提娜被派遣到了某个村子。\n从凯露那得知了大罪司教的动向后，\n众人认为那股神秘的能力十分危险，并赶往了现场。');
INSERT INTO hatsune_description VALUES(1001702003,10017,2,'一行人赶到了正陷入苦战的克莉丝提娜身边。\n本以为变得有利的局势又因魔女教徒的出现而陷入困境。\n有了爱蜜莉雅的助阵，【美食殿堂】以魔法的冰块\n隔开了培提尔其乌斯，开始进行最后的决战！');
INSERT INTO hatsune_description VALUES(1002802001,10028,2,'为了获得工作，杏奈前往溪谷的洞窟。\n七七香去寻找供应商，想要找到古代文献。\n听取了村民的请求后，流夏往村子走去。\n三人向着各自的目的地出发了。');
INSERT INTO hatsune_description VALUES(1002802002,10028,2,'流夏完美地惩戒了村子里的恶徒。\n在与害怕被报复的村民对话时，\n她察觉到了在溪谷一带暗中活动的邪恶存在。\n与此同时，杏奈也正朝着溪谷的洞窟移动……');
INSERT INTO hatsune_description VALUES(1002802003,10028,2,'杏奈等人开始在溪谷的洞窟工作，\n可那里与事先说好的完全不同，充满了无法无天的人，\n劳动也过于苛刻，环境非常恶劣。\n与此同时，七七香也来到了供应商的所在地……');
INSERT INTO hatsune_description VALUES(1002802004,10028,2,'但古代文献都被某位贵族垄断了，\n七七香没法进货。\n她在回去的路上竟被恶徒的袭击，\n想到应该尽快和流夏汇合，便匆匆赶向了村子……');
INSERT INTO hatsune_description VALUES(1002802005,10028,2,'得知了溪谷的洞窟就是恶徒们的大本营，\n流夏和七七香决定和杏奈她们汇合。\n她们救出了好不容易才逃出来的杏奈一行人，\n大家决定先离开洞窟。');
INSERT INTO hatsune_description VALUES(1003202001,10032,2,'在这座用于祈祷、净化的神殿中，\n没能实现的“实体化的愿望”会袭向人们，\n因此，优衣等人充当警卫的委托。\n大家为了获得报酬中的压岁钱，接受了这项委托。');
INSERT INTO hatsune_description VALUES(1003202002,10032,2,'尽管前来参拜的客人让几人手忙脚乱的，\n但她们还是齐心协力，完成了工作。\n就在这时，出现了一个想要寻找父母的“实体化的愿望”，\n最后被扮作亲切父母的日和莉等人所净化。');
INSERT INTO hatsune_description VALUES(1003202003,10032,2,'正当众人逐渐习惯这份工作时，又出现了想知道\n该如何与女朋友接吻的“实体化的愿望”。\n然而在看到主角因为想要保护快要摔倒的优衣，而差点和她亲上时，\n便直接被净化了。');
INSERT INTO hatsune_description VALUES(1003202004,10032,2,'随着夜晚临近，来参拜的客人也增加了，众人忙碌起来。\n此时又出现了“实体化的愿望”。\n“实体化的愿望”哀叹着想得到鼓励，\n在怜“尽力”的打气下得到了净化。');
INSERT INTO hatsune_description VALUES(1003202005,10032,2,'在净化了一个又一个愿望之后，大家得到了一段休息的时光。\n年末即将来临，这是愿望变得最为强烈的几个小时\n“实体化的愿望”接踵而至，\n失控的愿望变成了黑色的雾气，笼罩了整座神殿。');
CREATE INDEX 'hatsune_description_0_event_id_1_type' on 'hatsune_description'('event_id','type');
COMMIT;
