PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'pkb_pitcher_ball_type' ('pitcher_id' INTEGER NOT NULL, 'ball_type' INTEGER NOT NULL, 'ball_type_name' TEXT NOT NULL, PRIMARY KEY('pitcher_id','ball_type'));
INSERT INTO pkb_pitcher_ball_type VALUES(1,1,'ストレート');
INSERT INTO pkb_pitcher_ball_type VALUES(1,2,'カーブ');
INSERT INTO pkb_pitcher_ball_type VALUES(2,3,'ストレート');
INSERT INTO pkb_pitcher_ball_type VALUES(2,4,'シンカー');
INSERT INTO pkb_pitcher_ball_type VALUES(2,6,'Sカーブ');
INSERT INTO pkb_pitcher_ball_type VALUES(3,7,'ストレート');
INSERT INTO pkb_pitcher_ball_type VALUES(3,8,'カーブ');
INSERT INTO pkb_pitcher_ball_type VALUES(3,9,'スライダー');
INSERT INTO pkb_pitcher_ball_type VALUES(3,5,'シンカー');
INSERT INTO pkb_pitcher_ball_type VALUES(3,16,'シュート');
INSERT INTO pkb_pitcher_ball_type VALUES(3,10,'ハツネ☆イリュージョン');
INSERT INTO pkb_pitcher_ball_type VALUES(3,11,'ハツネ☆バニッシュ');
INSERT INTO pkb_pitcher_ball_type VALUES(4,12,'ストレート');
INSERT INTO pkb_pitcher_ball_type VALUES(4,13,'カーブ');
INSERT INTO pkb_pitcher_ball_type VALUES(4,14,'シンカー');
INSERT INTO pkb_pitcher_ball_type VALUES(4,17,'ドラゴンズエンドボール');
INSERT INTO pkb_pitcher_ball_type VALUES(4,18,'ドラゴンズテイル');
CREATE INDEX 'pkb_pitcher_ball_type_0_pitcher_id' on 'pkb_pitcher_ball_type'('pitcher_id');
COMMIT;
