PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'pkb_pitcher_ball_type' ('pitcher_id' INTEGER NOT NULL, 'ball_type' INTEGER NOT NULL, 'ball_type_name' TEXT NOT NULL, PRIMARY KEY('pitcher_id','ball_type'));
INSERT INTO pkb_pitcher_ball_type VALUES(1,1,'直球');
INSERT INTO pkb_pitcher_ball_type VALUES(1,2,'曲线球');
INSERT INTO pkb_pitcher_ball_type VALUES(2,3,'直球');
INSERT INTO pkb_pitcher_ball_type VALUES(2,4,'沉球');
INSERT INTO pkb_pitcher_ball_type VALUES(2,6,'S曲球');
INSERT INTO pkb_pitcher_ball_type VALUES(3,7,'直球');
INSERT INTO pkb_pitcher_ball_type VALUES(3,8,'曲线球');
INSERT INTO pkb_pitcher_ball_type VALUES(3,9,'滑球');
INSERT INTO pkb_pitcher_ball_type VALUES(3,5,'沉球');
INSERT INTO pkb_pitcher_ball_type VALUES(3,16,'喷射球');
INSERT INTO pkb_pitcher_ball_type VALUES(3,10,'初音☆幻象');
INSERT INTO pkb_pitcher_ball_type VALUES(3,11,'初音☆遁形');
INSERT INTO pkb_pitcher_ball_type VALUES(4,12,'直球');
INSERT INTO pkb_pitcher_ball_type VALUES(4,13,'曲线球');
INSERT INTO pkb_pitcher_ball_type VALUES(4,14,'沉球');
INSERT INTO pkb_pitcher_ball_type VALUES(4,17,'龙族终结球');
INSERT INTO pkb_pitcher_ball_type VALUES(4,18,'龙族长尾');
CREATE INDEX 'pkb_pitcher_ball_type_0_pitcher_id' on 'pkb_pitcher_ball_type'('pitcher_id');
COMMIT;
