PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'shiori_description' ('id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'description' TEXT NOT NULL, PRIMARY KEY('id'));
INSERT INTO shiori_description VALUES(101,1,'在外传中，可以观看特别的故事。\n活动剧情会根据活动关卡的通关进度解锁。');
INSERT INTO shiori_description VALUES(201,2,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(301,3,'挑战活动关卡和首领时，\n会触发信赖度章节。根据对话的结果，能提升信赖度，\n当信赖度达到一定程度时，还能获得礼物。');
INSERT INTO shiori_description VALUES(20005,4,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(20007,5,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(20009,6,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(20010,7,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(20011,8,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(20013,9,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
INSERT INTO shiori_description VALUES(20015,10,'完成任务后，会有可解锁的角色登场。\n努力完成任务吧。');
CREATE INDEX 'shiori_description_0_type' on 'shiori_description'('type');
COMMIT;
