PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
ANALYZE "sqlite_master";
INSERT INTO sqlite_stat1 VALUES('event_gacha_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz','hatsune_quiz_0_event_id','4 4');
INSERT INTO sqlite_stat1 VALUES('event_wave_group_data',NULL,'4518');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest_area','hatsune_quest_area_0_event_id','32 3');
INSERT INTO sqlite_stat1 VALUES('goldset_data_teamlevel',NULL,'150');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_story_condition',NULL,'105');
INSERT INTO sqlite_stat1 VALUES('clan_invite_level_group',NULL,'24');
INSERT INTO sqlite_stat1 VALUES('tower_quest_fix_reward_group',NULL,'238');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_mission_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('sekai_unlock_story_condition',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('dungeon_quest_data',NULL,'37');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','hatsune_special_battle_0_event_id','12 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','sqlite_autoindex_hatsune_special_battle_1','12 3 1');
INSERT INTO sqlite_stat1 VALUES('event_introduction',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('stamp',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('dungeon_area_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('event_boss_treasure_box',NULL,'43');
INSERT INTO sqlite_stat1 VALUES('grand_arena_max_season_rank_reward',NULL,'118');
INSERT INTO sqlite_stat1 VALUES('album_production_list','album_production_list_0_unit_id','632 8');
INSERT INTO sqlite_stat1 VALUES('still','still_0_story_id','391 2');
INSERT INTO sqlite_stat1 VALUES('fix_lineup_group_set','fix_lineup_group_set_0_team_level_from_1_team_level_to','22 3 2');
INSERT INTO sqlite_stat1 VALUES('fix_lineup_group_set','sqlite_autoindex_fix_lineup_group_set_1','22 4 1 1');
INSERT INTO sqlite_stat1 VALUES('sekai_top_data',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('room_release_data',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('music_content',NULL,'67');
INSERT INTO sqlite_stat1 VALUES('tower_ex_quest_data','tower_ex_quest_data_0_floor_num','6 1');
INSERT INTO sqlite_stat1 VALUES('event_enemy_parameter',NULL,'3764');
INSERT INTO sqlite_stat1 VALUES('room_emotion_icon',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_data',NULL,'327');
INSERT INTO sqlite_stat1 VALUES('pct_gaming_motion',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_unit_condition',NULL,'7');
INSERT INTO sqlite_stat1 VALUES('room_chat_formation',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_enemy',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('hatsune_map',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('room_item_announcement',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('pct_system_fruits',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('pct_system',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest_condition',NULL,'280');
INSERT INTO sqlite_stat1 VALUES('login_bonus_adv','login_bonus_adv_0_login_bonus_id','5 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_daily_mission_data',NULL,'23');
INSERT INTO sqlite_stat1 VALUES('login_bonus_message_data','login_bonus_message_data_0_login_bonus_id','91 46');
INSERT INTO sqlite_stat1 VALUES('pct_combo_coefficient',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('actual_unit_background',NULL,'77');
INSERT INTO sqlite_stat1 VALUES('room_effect_reward_get','sqlite_autoindex_room_effect_reward_get_1','57 7 1');
INSERT INTO sqlite_stat1 VALUES('position_setting',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period','clan_battle_period_0_clan_battle_id','12 1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period','sqlite_autoindex_clan_battle_period_1','12 1 1');
INSERT INTO sqlite_stat1 VALUES('room_chat_scenario','room_chat_scenario_0_id','274 11');
INSERT INTO sqlite_stat1 VALUES('room_chat_scenario','sqlite_autoindex_room_chat_scenario_1','274 11 1');
INSERT INTO sqlite_stat1 VALUES('login_bonus_detail','login_bonus_detail_0_login_bonus_id_1_count','121 10 2');
INSERT INTO sqlite_stat1 VALUES('unit_status_coefficient',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('sekai_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_last_attack_reward',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('clan_battle_schedule',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('unit_background',NULL,'80');
INSERT INTO sqlite_stat1 VALUES('hatsune_present','hatsune_present_0_event_id','2 1');
INSERT INTO sqlite_stat1 VALUES('clan_cost_group',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('navi_comment',NULL,'54');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_damage_rank_reward',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('grand_arena_max_rank_reward',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('unit_profile',NULL,'80');
INSERT INTO sqlite_stat1 VALUES('unlock_skill_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_group','clan_battle_boss_group_0_clan_battle_boss_group_id','170 5');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_group','sqlite_autoindex_clan_battle_boss_group_1','170 5 1');
INSERT INTO sqlite_stat1 VALUES('grand_arena_daily_rank_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_effect',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('room_chat_info',NULL,'25');
INSERT INTO sqlite_stat1 VALUES('unit_skill_data',NULL,'404');
INSERT INTO sqlite_stat1 VALUES('story_quest_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('vote_unit','sqlite_autoindex_vote_unit_1','55 55 1');
INSERT INTO sqlite_stat1 VALUES('pct_itempoint','pct_itempoint_0_item_id','3 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest','hatsune_quest_0_event_id','280 20');
INSERT INTO sqlite_stat1 VALUES('room_unit_comments','room_unit_comments_0_unit_id','2872 24');
INSERT INTO sqlite_stat1 VALUES('room_unit_comments','sqlite_autoindex_room_unit_comments_1','2872 24 8 2 1');
INSERT INTO sqlite_stat1 VALUES('tower_story_detail',NULL,'24');
INSERT INTO sqlite_stat1 VALUES('story_data',NULL,'107');
INSERT INTO sqlite_stat1 VALUES('gift_message',NULL,'63');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_data',NULL,'65');
INSERT INTO sqlite_stat1 VALUES('skill_action',NULL,'1753');
INSERT INTO sqlite_stat1 VALUES('goldset_data',NULL,'70');
INSERT INTO sqlite_stat1 VALUES('sekai_add_times_data',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('unit_unique_equip',NULL,'24');
INSERT INTO sqlite_stat1 VALUES('story_detail',NULL,'678');
INSERT INTO sqlite_stat1 VALUES('content_map_data',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('odds_name_data',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_boss_ticket_count',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_mode',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('gacha_data',NULL,'100');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','room_item_detail_0_lvup_trigger_type_2_1_lvup_trigger_id_2','387 387 387');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','room_item_detail_0_lvup_trigger_type_1_lvup_trigger_id','387 194 194');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','sqlite_autoindex_room_item_detail_1','387 2 1');
INSERT INTO sqlite_stat1 VALUES('quest_defeat_notice',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('pct_reward','pct_reward_0_pct_point_type','15 5');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_fix_reward',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_fix_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_setup',NULL,'274');
INSERT INTO sqlite_stat1 VALUES('event_navi_comment',NULL,'27');
INSERT INTO sqlite_stat1 VALUES('cooperation_quest_data',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('sekai_top_story_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('clan_grade',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('bg_data','sqlite_autoindex_bg_data_1','84 1');
INSERT INTO sqlite_stat1 VALUES('skill_data',NULL,'900');
INSERT INTO sqlite_stat1 VALUES('love_chara',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_damage_rank','clan_battle_boss_damage_rank_0_damage_rank_id','160 4');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_damage_rank','sqlite_autoindex_clan_battle_boss_damage_rank_1','160 4 1 1');
INSERT INTO sqlite_stat1 VALUES('wave_group_data',NULL,'1395');
INSERT INTO sqlite_stat1 VALUES('equipment_enhance_rate',NULL,'207');
INSERT INTO sqlite_stat1 VALUES('tower_enemy_parameter',NULL,'1162');
INSERT INTO sqlite_stat1 VALUES('content_release_data',NULL,'23');
INSERT INTO sqlite_stat1 VALUES('music_list',NULL,'57');
INSERT INTO sqlite_stat1 VALUES('event_top_adv','event_top_adv_0_event_id_1_type','86 11 3');
INSERT INTO sqlite_stat1 VALUES('gacha_exchange_lineup',NULL,'31');
INSERT INTO sqlite_stat1 VALUES('campaign_schedule',NULL,'147');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','unit_rarity_0_unit_material_id','490 7');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','unit_rarity_0_unit_id','490 5');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','sqlite_autoindex_unit_rarity_1','490 5 1');
INSERT INTO sqlite_stat1 VALUES('enemy_parameter',NULL,'2956');
INSERT INTO sqlite_stat1 VALUES('tower_area_data',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('event_boss_treasure_content',NULL,'196');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz_condition','hatsune_quiz_condition_0_event_id_1_quiz_id','6 6 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_mission_reward_data','hatsune_mission_reward_data_0_mission_reward_id','802 2');
INSERT INTO sqlite_stat1 VALUES('experience_team',NULL,'122');
INSERT INTO sqlite_stat1 VALUES('arena_daily_rank_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_change',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('story_character_mask',NULL,'264');
INSERT INTO sqlite_stat1 VALUES('tips',NULL,'58');
INSERT INTO sqlite_stat1 VALUES('clan_battle_odds_data','clan_battle_odds_data_0_odds_group_id','12 3');
INSERT INTO sqlite_stat1 VALUES('clan_battle_odds_data','sqlite_autoindex_clan_battle_odds_data_1','12 3 1 1');
INSERT INTO sqlite_stat1 VALUES('unit_data',NULL,'106');
INSERT INTO sqlite_stat1 VALUES('ailment_data',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('tower_quest_data','tower_quest_data_0_floor_num','190 1');
INSERT INTO sqlite_stat1 VALUES('minigame','minigame_0_event_id','1 1');
INSERT INTO sqlite_stat1 VALUES('resist_data',NULL,'27');
INSERT INTO sqlite_stat1 VALUES('room_item',NULL,'323');
INSERT INTO sqlite_stat1 VALUES('skill_cost',NULL,'124');
INSERT INTO sqlite_stat1 VALUES('notif_data','notif_data_0_unit_id','462 6');
INSERT INTO sqlite_stat1 VALUES('notif_data','sqlite_autoindex_notif_data_1','462 6 1');
INSERT INTO sqlite_stat1 VALUES('vote_info','sqlite_autoindex_vote_info_1','3 3 1');
INSERT INTO sqlite_stat1 VALUES('tower_schedule','tower_schedule_0_opening_story_id','6 1');
INSERT INTO sqlite_stat1 VALUES('event_enemy_reward_group',NULL,'137');
INSERT INTO sqlite_stat1 VALUES('hatsune_description',NULL,'64');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('arena_max_season_rank_reward',NULL,'118');
INSERT INTO sqlite_stat1 VALUES('unit_promotion_status','sqlite_autoindex_unit_promotion_status_1','946 11 1');
INSERT INTO sqlite_stat1 VALUES('unit_comments','unit_comments_0_unit_id_1_use_type','948 6 3');
INSERT INTO sqlite_stat1 VALUES('unit_comments','unit_comments_0_unit_id','948 6');
INSERT INTO sqlite_stat1 VALUES('quest_area_data',NULL,'45');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_data',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('pct_tap_speed',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('skip_monster_data',NULL,'657');
INSERT INTO sqlite_stat1 VALUES('enemy_reward_data',NULL,'1272');
INSERT INTO sqlite_stat1 VALUES('quest_condition_data',NULL,'363');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz_reward',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('tower_story_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('equipment_enhance_data','sqlite_autoindex_equipment_enhance_data_1','14 4 1');
INSERT INTO sqlite_stat1 VALUES('skip_boss_data',NULL,'28');
INSERT INTO sqlite_stat1 VALUES('global_data','sqlite_autoindex_global_data_1','2 1');
INSERT INTO sqlite_stat1 VALUES('seasonpasspoint_mission_data',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('pct_result','pct_result_0_character_id','4 2');
INSERT INTO sqlite_stat1 VALUES('shop_static_price_group',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('clan_battle_map_data',NULL,'34');
INSERT INTO sqlite_stat1 VALUES('event_bg_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('grand_arena_defence_reward',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_schedule',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('unit_mypage_pos',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('unlock_unit_condition',NULL,'75');
INSERT INTO sqlite_stat1 VALUES('equipment_donation',NULL,'9');
INSERT INTO sqlite_stat1 VALUES('daily_mission_data',NULL,'362');
INSERT INTO sqlite_stat1 VALUES('equipment_data',NULL,'377');
INSERT INTO sqlite_stat1 VALUES('tower_wave_group_data',NULL,'238');
INSERT INTO sqlite_stat1 VALUES('login_bonus_data',NULL,'13');
INSERT INTO sqlite_stat1 VALUES('unit_attack_pattern',NULL,'513');
INSERT INTO sqlite_stat1 VALUES('chara_story_status',NULL,'461');
INSERT INTO sqlite_stat1 VALUES('seasonpass_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('visual_customize',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('pct_evaluation',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss_condition',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('sekai_enemy_parameter',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period_rank_reward',NULL,'180');
INSERT INTO sqlite_stat1 VALUES('event_story_detail','event_story_detail_0_story_group_id','97 9');
INSERT INTO sqlite_stat1 VALUES('worldmap',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('training_quest_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_reward',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('experience_unit',NULL,'122');
INSERT INTO sqlite_stat1 VALUES('vote_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('event_story_data','event_story_data_0_value','12 1');
INSERT INTO sqlite_stat1 VALUES('equipment_craft',NULL,'170');
INSERT INTO sqlite_stat1 VALUES('hatsune_stationary_mission_data',NULL,'342');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_craft',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('hatsune_map_event','hatsune_map_event_0_target_event_id','40 10');
INSERT INTO sqlite_stat1 VALUES('movie',NULL,'114');
INSERT INTO sqlite_stat1 VALUES('chara_identity',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('character_love_rankup_text',NULL,'42');
INSERT INTO sqlite_stat1 VALUES('arena_defence_reward',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('banner',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('stationary_mission_data',NULL,'494');
INSERT INTO sqlite_stat1 VALUES('unit_enemy_data',NULL,'325');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_enhance_data','sqlite_autoindex_unique_equipment_enhance_data_1','129 129 1');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_enhance_rate',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('hatsune_item',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('unit_motion_list',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_rankup','unique_equipment_rankup_0_equip_id','180 5');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_rankup','sqlite_autoindex_unique_equipment_rankup_1','180 5 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_schedule',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('room_character_personality',NULL,'80');
INSERT INTO sqlite_stat1 VALUES('unit_promotion','unit_promotion_0_unit_id','1232 12');
INSERT INTO sqlite_stat1 VALUES('unit_promotion','sqlite_autoindex_unit_promotion_1','1232 12 1');
INSERT INTO sqlite_stat1 VALUES('item_data',NULL,'123');
INSERT INTO sqlite_stat1 VALUES('reward_collect_guide',NULL,'426');
INSERT INTO sqlite_stat1 VALUES('arena_max_rank_reward',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('seasonpassnormal_mission_data',NULL,'151');
INSERT INTO sqlite_stat1 VALUES('hatsune_bg_change',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('guild',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('mission_reward_data','mission_reward_data_0_mission_reward_id','234 3');
INSERT INTO sqlite_stat1 VALUES('album_voice_list','album_voice_list_0_unit_id','3182 37');
INSERT INTO sqlite_stat1 VALUES('season_pack','season_pack_0_mission_id','3 2');
INSERT INTO sqlite_stat1 VALUES('unit_introduction','unit_introduction_0_gacha_id','27 1');
INSERT INTO sqlite_stat1 VALUES('quest_reward_data',NULL,'754');
INSERT INTO sqlite_stat1 VALUES('quest_data',NULL,'363');
COMMIT;
