PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
ANALYZE "sqlite_master";
INSERT INTO sqlite_stat1 VALUES('event_gacha_data','event_gacha_data_0_event_id','60 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz','hatsune_quiz_0_event_id_1_release_quest_id','8 4 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz','hatsune_quiz_0_event_id','8 4');
INSERT INTO sqlite_stat1 VALUES('goldset_data_2',NULL,'70');
INSERT INTO sqlite_stat1 VALUES('serial_group_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('ttk_drama','ttk_drama_0_drama_id','62 11');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_story_condition','hatsune_unlock_story_condition_0_event_id','326 9');
INSERT INTO sqlite_stat1 VALUES('clan_invite_level_group',NULL,'37');
INSERT INTO sqlite_stat1 VALUES('ssp_story_data','ssp_story_data_0_contents_type','22 6');
INSERT INTO sqlite_stat1 VALUES('ssp_story_data','ssp_story_data_0_original_event_id','22 22');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','hatsune_special_battle_0_wave_group_id','141 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','hatsune_special_battle_0_event_id','141 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','sqlite_autoindex_hatsune_special_battle_1','141 3 1');
INSERT INTO sqlite_stat1 VALUES('event_introduction','event_introduction_0_event_id','58 1');
INSERT INTO sqlite_stat1 VALUES('stamp',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('dungeon_area_data',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss_enemy_setting','hatsune_boss_enemy_setting_0_boss_id_1_event_id','15 3 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss_enemy_setting','sqlite_autoindex_hatsune_boss_enemy_setting_1','15 3 1');
INSERT INTO sqlite_stat1 VALUES('fix_lineup_group_set','fix_lineup_group_set_0_team_level_from_1_team_level_to','24 3 2');
INSERT INTO sqlite_stat1 VALUES('fix_lineup_group_set','sqlite_autoindex_fix_lineup_group_set_1','24 4 1 1');
INSERT INTO sqlite_stat1 VALUES('sekai_top_data','sekai_top_data_0_sekai_id','22 11');
INSERT INTO sqlite_stat1 VALUES('room_release_data',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('fke_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('nyx_phase_data',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('event_boss_treasure_box',NULL,'242');
INSERT INTO sqlite_stat1 VALUES('shiori_event_list',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('grand_arena_max_season_rank_reward',NULL,'118');
INSERT INTO sqlite_stat1 VALUES('birthday_login_bonus_data',NULL,'61');
INSERT INTO sqlite_stat1 VALUES('serial_code_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('pct_system_fruits',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('pct_system',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest_condition','hatsune_quest_condition_0_event_id','1320 20');
INSERT INTO sqlite_stat1 VALUES('login_bonus_adv','login_bonus_adv_0_login_bonus_id','15 3');
INSERT INTO sqlite_stat1 VALUES('ske_story_script','ske_story_script_0_story_id','737 67');
INSERT INTO sqlite_stat1 VALUES('event_wave_group_data',NULL,'4518');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest_area','hatsune_quest_area_0_event_id','139 3');
INSERT INTO sqlite_stat1 VALUES('goldset_data_teamlevel',NULL,'200');
INSERT INTO sqlite_stat1 VALUES('nyx_story_script','nyx_story_script_0_story_id','785 72');
INSERT INTO sqlite_stat1 VALUES('dear_setting',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('arena_max_rank_reward',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('birthday_login_bonus_drama_script','birthday_login_bonus_drama_script_0_drama_id','491 62');
INSERT INTO sqlite_stat1 VALUES('growth_restriction_unit','growth_restriction_unit_0_growth_id','4 1');
INSERT INTO sqlite_stat1 VALUES('pct_combo_coefficient',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha_data',NULL,'48');
INSERT INTO sqlite_stat1 VALUES('actual_unit_background',NULL,'146');
INSERT INTO sqlite_stat1 VALUES('room_effect_reward_get','sqlite_autoindex_room_effect_reward_get_1','87 8 1');
INSERT INTO sqlite_stat1 VALUES('voice_group',NULL,'108');
INSERT INTO sqlite_stat1 VALUES('seasonpass_mission_data',NULL,'67');
INSERT INTO sqlite_stat1 VALUES('seasonpass_foundation',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('fke_happening_list',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('tme_map_data','tme_map_data_0_event_id','12 12');
INSERT INTO sqlite_stat1 VALUES('uek_mission',NULL,'16');
INSERT INTO sqlite_stat1 VALUES('glossary_detail',NULL,'81');
INSERT INTO sqlite_stat1 VALUES('position_setting',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period','clan_battle_period_0_clan_battle_id','36 1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period','sqlite_autoindex_clan_battle_period_1','36 1 1');
INSERT INTO sqlite_stat1 VALUES('room_chat_scenario','room_chat_scenario_0_id','277 10');
INSERT INTO sqlite_stat1 VALUES('room_chat_scenario','sqlite_autoindex_room_chat_scenario_1','277 10 1');
INSERT INTO sqlite_stat1 VALUES('login_bonus_detail','login_bonus_detail_0_login_bonus_id_1_count','207 9 2');
INSERT INTO sqlite_stat1 VALUES('unit_status_coefficient',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('ttk_story','ttk_story_0_ttk_score','5 1');
INSERT INTO sqlite_stat1 VALUES('sekai_schedule',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('prizegacha_data',NULL,'34');
INSERT INTO sqlite_stat1 VALUES('clan_battle_last_attack_reward',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('clan_battle_schedule',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('growth_parameter',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('unit_background',NULL,'153');
INSERT INTO sqlite_stat1 VALUES('kaiser_special_battle',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('pkb_pitcher_ball_type','pkb_pitcher_ball_type_0_pitcher_id','17 5');
INSERT INTO sqlite_stat1 VALUES('pkb_pitcher_ball_type','sqlite_autoindex_pkb_pitcher_ball_type_1','17 5 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_present','hatsune_present_0_event_id','6 1');
INSERT INTO sqlite_stat1 VALUES('clan_cost_group',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('navi_comment',NULL,'77');
INSERT INTO sqlite_stat1 VALUES('space_top_data','space_top_data_0_story_id','8 2');
INSERT INTO sqlite_stat1 VALUES('space_top_data','space_top_data_0_space_id','8 8');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_data','hatsune_diary_data_0_contents_type','17 9');
INSERT INTO sqlite_stat1 VALUES('grand_arena_daily_rank_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_effect',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('room_chat_info',NULL,'28');
INSERT INTO sqlite_stat1 VALUES('unit_skill_data',NULL,'1048');
INSERT INTO sqlite_stat1 VALUES('pkb_batter_condition',NULL,'9');
INSERT INTO sqlite_stat1 VALUES('lto_letter_script','lto_letter_script_0_letter_id','54 54');
INSERT INTO sqlite_stat1 VALUES('album_production_list','album_production_list_0_unit_id','1356 9');
INSERT INTO sqlite_stat1 VALUES('still','still_0_still_group_id','935 5');
INSERT INTO sqlite_stat1 VALUES('still','still_0_story_id','935 2');
INSERT INTO sqlite_stat1 VALUES('special_story_banner','special_story_banner_0_story_group_id','1 1');
INSERT INTO sqlite_stat1 VALUES('srt_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('event_reminder','event_reminder_0_event_id','4 2');
INSERT INTO sqlite_stat1 VALUES('event_revival_wave_group_data',NULL,'4518');
INSERT INTO sqlite_stat1 VALUES('shiori_stationary_mission_data',NULL,'276');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha_sp',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('story_quest_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('seasonpass_mission_reward_data','seasonpass_mission_reward_data_0_mission_reward_id','18 2');
INSERT INTO sqlite_stat1 VALUES('shiori_boss_condition',NULL,'42');
INSERT INTO sqlite_stat1 VALUES('special_still',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('voice_group_chara',NULL,'75');
INSERT INTO sqlite_stat1 VALUES('dear_story_detail','dear_story_detail_0_story_group_id','417 27');
INSERT INTO sqlite_stat1 VALUES('dear_story_detail','dear_story_detail_0_story_group_id_1_chara_index','417 27 9');
INSERT INTO sqlite_stat1 VALUES('nyx_story_data','nyx_story_data_0_story_phase','15 5');
INSERT INTO sqlite_stat1 VALUES('nyx_story_data','nyx_story_data_0_story_seq','15 1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_s_boss_data',NULL,'190');
INSERT INTO sqlite_stat1 VALUES('clan_battle_2_map_data','clan_battle_2_map_data_0_clan_battle_id','154 5');
INSERT INTO sqlite_stat1 VALUES('story_data',NULL,'193');
INSERT INTO sqlite_stat1 VALUES('spskill_label_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_script','hatsune_diary_script_0_diary_id','427 31');
INSERT INTO sqlite_stat1 VALUES('gift_message',NULL,'109');
INSERT INTO sqlite_stat1 VALUES('skill_action',NULL,'5878');
INSERT INTO sqlite_stat1 VALUES('kaiser_extermination_reward',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('emblem_data',NULL,'612');
INSERT INTO sqlite_stat1 VALUES('vote_unit','sqlite_autoindex_vote_unit_1','55 55 1');
INSERT INTO sqlite_stat1 VALUES('pct_itempoint','pct_itempoint_0_item_id','3 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_setting',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest','hatsune_quest_0_event_id','1200 20');
INSERT INTO sqlite_stat1 VALUES('room_unit_comments','room_unit_comments_0_unit_id','4591 24');
INSERT INTO sqlite_stat1 VALUES('room_unit_comments','sqlite_autoindex_room_unit_comments_1','4591 24 8 2 1');
INSERT INTO sqlite_stat1 VALUES('tower_story_detail',NULL,'96');
INSERT INTO sqlite_stat1 VALUES('quest_annihilation','sqlite_autoindex_quest_annihilation_1','2 2 1');
INSERT INTO sqlite_stat1 VALUES('pkb_drama_data',NULL,'38');
INSERT INTO sqlite_stat1 VALUES('srt_score',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('hatsune_daily_mission_data',NULL,'117');
INSERT INTO sqlite_stat1 VALUES('login_bonus_message_data','login_bonus_message_data_0_login_bonus_id','330 66');
INSERT INTO sqlite_stat1 VALUES('rarity_6_quest_data','rarity_6_quest_data_0_rarity_6_quest_id','23 1');
INSERT INTO sqlite_stat1 VALUES('shiori_enemy_parameter',NULL,'7328');
INSERT INTO sqlite_stat1 VALUES('goldset_data',NULL,'70');
INSERT INTO sqlite_stat1 VALUES('sekai_add_times_data',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('clan_battle_s_map_data','clan_battle_s_map_data_0_clan_battle_id','134 4');
INSERT INTO sqlite_stat1 VALUES('unit_unique_equip',NULL,'104');
INSERT INTO sqlite_stat1 VALUES('story_detail',NULL,'1248');
INSERT INTO sqlite_stat1 VALUES('content_map_data',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('odds_name_data',NULL,'145');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_boss_ticket_count',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_mode',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('gacha_data',NULL,'390');
INSERT INTO sqlite_stat1 VALUES('room_character_skin_color',NULL,'150');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','room_item_detail_0_lvup_trigger_type_2_1_lvup_trigger_id_2','540 540 540');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','room_item_detail_0_lvup_trigger_type_1_lvup_trigger_id','540 270 270');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','sqlite_autoindex_room_item_detail_1','540 2 1');
INSERT INTO sqlite_stat1 VALUES('quest_defeat_notice',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('space_battle_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('space_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('pct_evaluation',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('uek_spine_anim_link','uek_spine_anim_link_0_anim_num','50 13');
INSERT INTO sqlite_stat1 VALUES('hatsune_multi_route_parameter','hatsune_multi_route_parameter_0_type','20 5');
INSERT INTO sqlite_stat1 VALUES('hatsune_multi_route_parameter','hatsune_multi_route_parameter_0_quest_id','20 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss_condition',NULL,'254');
INSERT INTO sqlite_stat1 VALUES('sekai_enemy_parameter',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period_rank_reward',NULL,'540');
INSERT INTO sqlite_stat1 VALUES('event_story_detail','event_story_detail_0_story_group_id','314 9');
INSERT INTO sqlite_stat1 VALUES('worldmap',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('training_quest_data',NULL,'22');
INSERT INTO sqlite_stat1 VALUES('event_reminder_condition','event_reminder_condition_0_reminder_id','4 1');
INSERT INTO sqlite_stat1 VALUES('unit_introduction','unit_introduction_0_gacha_id','112 1');
INSERT INTO sqlite_stat1 VALUES('quest_reward_data',NULL,'3052');
INSERT INTO sqlite_stat1 VALUES('quest_data',NULL,'797');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_reward_data','emblem_mission_reward_data_0_reward_id','729 2');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_reward_data','emblem_mission_reward_data_0_mission_reward_id','729 2');
INSERT INTO sqlite_stat1 VALUES('tower_quest_fix_reward_group',NULL,'581');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_mission_data',NULL,'329');
INSERT INTO sqlite_stat1 VALUES('sekai_unlock_story_condition',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('dungeon_quest_data',NULL,'47');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_reward_data','campaign_mission_reward_data_0_campaign_mission_reward_id','24 2');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_data',NULL,'514');
INSERT INTO sqlite_stat1 VALUES('pct_gaming_motion',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('dear_reward','dear_reward_0_event_id_1_chara_index','260 15 5');
INSERT INTO sqlite_stat1 VALUES('shiori_mission_reward_data','shiori_mission_reward_data_0_mission_reward_id','637 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_unit_condition','hatsune_unlock_unit_condition_0_condition_mission_id','38 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_unit_condition','hatsune_unlock_unit_condition_0_unit_id_1_event_id','38 2 1');
INSERT INTO sqlite_stat1 VALUES('room_chat_formation',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_data','campaign_mission_data_0_campaign_id_1_type','28 14 7');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_data','campaign_mission_data_0_campaign_id','28 14');
INSERT INTO sqlite_stat1 VALUES('hatsune_relay_data',NULL,'48');
INSERT INTO sqlite_stat1 VALUES('custom_mypage_group',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('album_voice_list','album_voice_list_0_unit_id','3182 37');
INSERT INTO sqlite_stat1 VALUES('season_pack','season_pack_0_mission_id','27 5');
INSERT INTO sqlite_stat1 VALUES('tower_cloister_quest_data',NULL,'19');
INSERT INTO sqlite_stat1 VALUES('hatsune_bg_change',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('custom_mypage','custom_mypage_0_still_group_id','95 95');
INSERT INTO sqlite_stat1 VALUES('guild',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('mission_reward_data','mission_reward_data_0_mission_reward_id','622 4');
INSERT INTO sqlite_stat1 VALUES('ttk_score',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('tower_area_data',NULL,'30');
INSERT INTO sqlite_stat1 VALUES('event_boss_treasure_content',NULL,'1250');
INSERT INTO sqlite_stat1 VALUES('shiori_unlock_unit_condition','shiori_unlock_unit_condition_0_condition_mission_id','7 1');
INSERT INTO sqlite_stat1 VALUES('shiori_unlock_unit_condition','shiori_unlock_unit_condition_0_unit_id_1_event_id','7 1 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz_condition','hatsune_quiz_condition_0_event_id_1_quiz_id','12 6 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_mission_reward_data','hatsune_mission_reward_data_0_mission_reward_id','4259 2');
INSERT INTO sqlite_stat1 VALUES('sd_navi_comment',NULL,'9');
INSERT INTO sqlite_stat1 VALUES('experience_team',NULL,'191');
INSERT INTO sqlite_stat1 VALUES('omp_drama','omp_drama_0_drama_id','601 67');
INSERT INTO sqlite_stat1 VALUES('arena_daily_rank_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_change',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_rail',NULL,'86');
INSERT INTO sqlite_stat1 VALUES('story_character_mask',NULL,'524');
INSERT INTO sqlite_stat1 VALUES('tips',NULL,'89');
INSERT INTO sqlite_stat1 VALUES('arcade_list',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('kaiser_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('pkb_drama','pkb_drama_0_drama_id','429 12');
INSERT INTO sqlite_stat1 VALUES('tower_quest_data','tower_quest_data_0_floor_num','510 1');
INSERT INTO sqlite_stat1 VALUES('minigame','minigame_0_event_id','6 1');
INSERT INTO sqlite_stat1 VALUES('event_series_wave_group_data',NULL,'4518');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period_lap_reward',NULL,'256');
INSERT INTO sqlite_stat1 VALUES('clan_battle_2_boss_data',NULL,'190');
INSERT INTO sqlite_stat1 VALUES('room_skin_color',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('resist_data',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('nyx_drama_script','nyx_drama_script_0_drama_id','735 74');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_enemy',NULL,'130');
INSERT INTO sqlite_stat1 VALUES('hatsune_map',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('room_item_announcement',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('enemy_m_parts',NULL,'136');
INSERT INTO sqlite_stat1 VALUES('ttk_story_script','ttk_story_script_0_story_id','227 46');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_reward',NULL,'28');
INSERT INTO sqlite_stat1 VALUES('experience_unit',NULL,'191');
INSERT INTO sqlite_stat1 VALUES('vote_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('event_story_data','event_story_data_0_value','38 1');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_schedule',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('equipment_craft',NULL,'314');
INSERT INTO sqlite_stat1 VALUES('shiori_wave_group_data',NULL,'840');
INSERT INTO sqlite_stat1 VALUES('hatsune_stationary_mission_data','hatsune_stationary_mission_data_0_event_id','1901 32');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_material_id','161 4');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_unit_id_1_unlock_level','161 7 2');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_unit_id_1_slot_id','161 7 3');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_unit_id','161 7');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','sqlite_autoindex_unlock_rarity_6_1','161 7 3 1');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_craft',NULL,'111');
INSERT INTO sqlite_stat1 VALUES('item_e_ticket_data','item_e_ticket_data_0_exchange_number','27 7');
INSERT INTO sqlite_stat1 VALUES('item_e_ticket_data','item_e_ticket_data_0_ticket_id','27 3');
INSERT INTO sqlite_stat1 VALUES('item_e_ticket_data','sqlite_autoindex_item_e_ticket_data_1','27 3 1');
INSERT INTO sqlite_stat1 VALUES('pkb_reward',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('clan_battle_odds_data','clan_battle_odds_data_0_odds_group_id','26 6');
INSERT INTO sqlite_stat1 VALUES('clan_battle_odds_data','sqlite_autoindex_clan_battle_odds_data_1','26 6 1 1');
INSERT INTO sqlite_stat1 VALUES('unit_data',NULL,'184');
INSERT INTO sqlite_stat1 VALUES('ailment_data',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('kmk_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('pct_tap_speed',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('skip_monster_data',NULL,'2485');
INSERT INTO sqlite_stat1 VALUES('quest_condition_data',NULL,'804');
INSERT INTO sqlite_stat1 VALUES('enemy_enable_voice',NULL,'70');
INSERT INTO sqlite_stat1 VALUES('clanprofile_content',NULL,'35');
INSERT INTO sqlite_stat1 VALUES('enemy_reward_data',NULL,'3093');
INSERT INTO sqlite_stat1 VALUES('dungeon_skip_data',NULL,'7');
INSERT INTO sqlite_stat1 VALUES('room_item',NULL,'454');
INSERT INTO sqlite_stat1 VALUES('clan_battle_training_data','clan_battle_training_data_0_training_id','5 5');
INSERT INTO sqlite_stat1 VALUES('skill_cost',NULL,'196');
INSERT INTO sqlite_stat1 VALUES('notif_data','notif_data_0_unit_id','900 6');
INSERT INTO sqlite_stat1 VALUES('notif_data','sqlite_autoindex_notif_data_1','900 6 1');
INSERT INTO sqlite_stat1 VALUES('arcade_story_list','arcade_story_list_0_arcade_id','14 5');
INSERT INTO sqlite_stat1 VALUES('omp_story_data','omp_story_data_0_story_seq','15 1');
INSERT INTO sqlite_stat1 VALUES('omp_story_data','omp_story_data_0_event_id','15 8');
INSERT INTO sqlite_stat1 VALUES('uek_boss','uek_boss_0_enemy_id','4 1');
INSERT INTO sqlite_stat1 VALUES('unlock_skill_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('myprofile_content',NULL,'24');
INSERT INTO sqlite_stat1 VALUES('kaiser_quest_data',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('vote_info','sqlite_autoindex_vote_info_1','3 3 1');
INSERT INTO sqlite_stat1 VALUES('tower_schedule','tower_schedule_0_opening_story_id','30 1');
INSERT INTO sqlite_stat1 VALUES('event_enemy_reward_group',NULL,'137');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_letter_script','hatsune_diary_letter_script_0_diary_id','151 51');
INSERT INTO sqlite_stat1 VALUES('hatsune_description','hatsune_description_0_event_id_1_type','384 6 3');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha',NULL,'16');
INSERT INTO sqlite_stat1 VALUES('clan_battle_recommend_data','clan_battle_recommend_data_0_recommend_group','9 3');
INSERT INTO sqlite_stat1 VALUES('arena_max_season_rank_reward',NULL,'118');
INSERT INTO sqlite_stat1 VALUES('unit_promotion_status','sqlite_autoindex_unit_promotion_status_1','3040 19 1');
INSERT INTO sqlite_stat1 VALUES('unit_comments','unit_comments_0_unit_id_1_use_type','1963 6 4');
INSERT INTO sqlite_stat1 VALUES('unit_comments','unit_comments_0_unit_id','1963 6');
INSERT INTO sqlite_stat1 VALUES('dear_story_data','dear_story_data_0_value','16 1');
INSERT INTO sqlite_stat1 VALUES('quest_area_data',NULL,'102');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_data',NULL,'111');
INSERT INTO sqlite_stat1 VALUES('music_list',NULL,'164');
INSERT INTO sqlite_stat1 VALUES('event_top_adv','event_top_adv_0_event_id_1_type','687 11 4');
INSERT INTO sqlite_stat1 VALUES('shiori_boss','shiori_boss_0_wave_group_id_1','36 1');
INSERT INTO sqlite_stat1 VALUES('shiori_boss','shiori_boss_0_event_id_1_difficulty','36 3 1');
INSERT INTO sqlite_stat1 VALUES('shiori_boss','shiori_boss_0_event_id','36 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_bg_change_data','hatsune_bg_change_data_0_target_type_1_area_id','21 11 2');
INSERT INTO sqlite_stat1 VALUES('gacha_exchange_lineup','gacha_exchange_lineup_0_exchange_id','197 2');
INSERT INTO sqlite_stat1 VALUES('campaign_schedule',NULL,'720');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','unit_rarity_0_unit_material_id','883 6');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','unit_rarity_0_unit_id','883 6');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','sqlite_autoindex_unit_rarity_1','883 6 1');
INSERT INTO sqlite_stat1 VALUES('enemy_parameter',NULL,'8813');
INSERT INTO sqlite_stat1 VALUES('tower_enemy_parameter',NULL,'3039');
INSERT INTO sqlite_stat1 VALUES('ticket_gacha_data',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('content_release_data',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_damage_rank_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('grand_arena_max_rank_reward',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('combined_result_motion',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('unit_profile',NULL,'157');
INSERT INTO sqlite_stat1 VALUES('specialfes_banner',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('ttk_weapon','ttk_weapon_0_ttk_score','4 1');
INSERT INTO sqlite_stat1 VALUES('tower_wave_group_data',NULL,'619');
INSERT INTO sqlite_stat1 VALUES('login_bonus_data',NULL,'25');
INSERT INTO sqlite_stat1 VALUES('unit_attack_pattern',NULL,'1259');
INSERT INTO sqlite_stat1 VALUES('chara_story_status',NULL,'820');
INSERT INTO sqlite_stat1 VALUES('visual_customize',NULL,'13');
INSERT INTO sqlite_stat1 VALUES('music_content',NULL,'170');
INSERT INTO sqlite_stat1 VALUES('tower_ex_quest_data','tower_ex_quest_data_0_floor_num','30 1');
INSERT INTO sqlite_stat1 VALUES('event_enemy_parameter',NULL,'3764');
INSERT INTO sqlite_stat1 VALUES('shiori_description','shiori_description_0_type','9 1');
INSERT INTO sqlite_stat1 VALUES('shiori_quest_area','shiori_quest_area_0_event_id','27 3');
INSERT INTO sqlite_stat1 VALUES('room_emotion_icon',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('spskill_lv_initialize_data',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('return_specialfes_banner',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('hatsune_emblem_mission','hatsune_emblem_mission_0_event_id','109 5');
INSERT INTO sqlite_stat1 VALUES('sekai_top_story_data','sekai_top_story_data_0_sekai_id','4 4');
INSERT INTO sqlite_stat1 VALUES('clan_grade',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('room_item_get_announcement',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('bg_data','sqlite_autoindex_bg_data_1','147 1');
INSERT INTO sqlite_stat1 VALUES('ttk_enemy',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_scenario',NULL,'52');
INSERT INTO sqlite_stat1 VALUES('skill_data',NULL,'2488');
INSERT INTO sqlite_stat1 VALUES('love_chara',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss','hatsune_boss_0_wave_group_id_1','254 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss','hatsune_boss_0_event_id_1_difficulty','254 5 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss','hatsune_boss_0_event_id','254 5');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_damage_rank','clan_battle_boss_damage_rank_0_damage_rank_id','160 4');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_damage_rank','sqlite_autoindex_clan_battle_boss_damage_rank_1','160 4 1 1');
INSERT INTO sqlite_stat1 VALUES('wave_group_data',NULL,'3986');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_category','campaign_mission_category_0_campaign_id_1_type','4 2 1');
INSERT INTO sqlite_stat1 VALUES('equipment_enhance_rate',NULL,'351');
INSERT INTO sqlite_stat1 VALUES('kaiser_restriction_group','kaiser_restriction_group_0_restriction_group_id','102 21');
INSERT INTO sqlite_stat1 VALUES('kaiser_restriction_group','sqlite_autoindex_kaiser_restriction_group_1','102 21 1');
INSERT INTO sqlite_stat1 VALUES('srt_top_talk','srt_top_talk_0_talk_id','45 2');
INSERT INTO sqlite_stat1 VALUES('srt_panel','srt_panel_0_version','438 438');
INSERT INTO sqlite_stat1 VALUES('srt_panel','srt_panel_0_panel_id','438 4');
INSERT INTO sqlite_stat1 VALUES('nyx_drama_data',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('skip_boss_data',NULL,'112');
INSERT INTO sqlite_stat1 VALUES('global_data','sqlite_autoindex_global_data_1','2 1');
INSERT INTO sqlite_stat1 VALUES('ttk_navi_comment',NULL,'13');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz_reward',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('tower_story_data',NULL,'16');
INSERT INTO sqlite_stat1 VALUES('equipment_enhance_data','sqlite_autoindex_equipment_enhance_data_1','19 4 1');
INSERT INTO sqlite_stat1 VALUES('pct_result','pct_result_0_character_id','4 2');
INSERT INTO sqlite_stat1 VALUES('shop_static_price_group',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('event_bg_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('birthday_login_bonus_detail','birthday_login_bonus_detail_0_login_bonus_id','78 2');
INSERT INTO sqlite_stat1 VALUES('profile_frame',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('seasonpass_level_reward',NULL,'100');
INSERT INTO sqlite_stat1 VALUES('event_effect_setting','sqlite_autoindex_event_effect_setting_1','48 3 1');
INSERT INTO sqlite_stat1 VALUES('grand_arena_defence_reward',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_schedule',NULL,'7');
INSERT INTO sqlite_stat1 VALUES('unit_mypage_pos',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('unlock_unit_condition',NULL,'145');
INSERT INTO sqlite_stat1 VALUES('daily_mission_data',NULL,'394');
INSERT INTO sqlite_stat1 VALUES('equipment_donation',NULL,'9');
INSERT INTO sqlite_stat1 VALUES('equipment_data',NULL,'665');
INSERT INTO sqlite_stat1 VALUES('hatsune_map_event','hatsune_map_event_0_target_event_id','121 9');
INSERT INTO sqlite_stat1 VALUES('movie','movie_0_story_id','299 2');
INSERT INTO sqlite_stat1 VALUES('chara_identity',NULL,'153');
INSERT INTO sqlite_stat1 VALUES('define_spskill','define_spskill_0_sp_skill_id','3 1');
INSERT INTO sqlite_stat1 VALUES('character_love_rankup_text',NULL,'42');
INSERT INTO sqlite_stat1 VALUES('srt_action','sqlite_autoindex_srt_action_1','41 1');
INSERT INTO sqlite_stat1 VALUES('shiori_item',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('arena_defence_reward',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('banner',NULL,'144');
INSERT INTO sqlite_stat1 VALUES('stationary_mission_data',NULL,'1200');
INSERT INTO sqlite_stat1 VALUES('lto_story_data','lto_story_data_0_event_id','1 1');
INSERT INTO sqlite_stat1 VALUES('dear_chara','dear_chara_0_event_id','47 3');
INSERT INTO sqlite_stat1 VALUES('dear_chara','sqlite_autoindex_dear_chara_1','47 3 1');
INSERT INTO sqlite_stat1 VALUES('unit_enemy_data',NULL,'926');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_enhance_data','sqlite_autoindex_unique_equipment_enhance_data_1','199 199 1');
INSERT INTO sqlite_stat1 VALUES('kmk_navi_comment',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('ske_story_data','ske_story_data_0_original_event_id','12 6');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_enhance_rate',NULL,'111');
INSERT INTO sqlite_stat1 VALUES('hatsune_item',NULL,'66');
INSERT INTO sqlite_stat1 VALUES('unit_motion_list',NULL,'152');
INSERT INTO sqlite_stat1 VALUES('dodge_tp_recovery',NULL,'39');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_rankup','unique_equipment_rankup_0_equip_id','1221 11');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_rankup','sqlite_autoindex_unique_equipment_rankup_1','1221 11 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_emblem_mission_reward','hatsune_emblem_mission_reward_0_reward_id','231 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_emblem_mission_reward','hatsune_emblem_mission_reward_0_mission_reward_id','231 2');
INSERT INTO sqlite_stat1 VALUES('pkb_navi_comment',NULL,'33');
INSERT INTO sqlite_stat1 VALUES('hatsune_schedule','hatsune_schedule_0_original_event_id','61 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_schedule','hatsune_schedule_0_series_event_id','61 21');
INSERT INTO sqlite_stat1 VALUES('room_character_personality',NULL,'155');
INSERT INTO sqlite_stat1 VALUES('guild_additional_member',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('unit_promotion','unit_promotion_0_unit_id','3520 20');
INSERT INTO sqlite_stat1 VALUES('unit_promotion','sqlite_autoindex_unit_promotion_1','3520 20 1');
INSERT INTO sqlite_stat1 VALUES('item_data',NULL,'331');
INSERT INTO sqlite_stat1 VALUES('ttk_reward','ttk_reward_0_ttk_score','2 1');
INSERT INTO sqlite_stat1 VALUES('event_navi_comment_condition',NULL,'253');
INSERT INTO sqlite_stat1 VALUES('shiori_quest_condition',NULL,'240');
INSERT INTO sqlite_stat1 VALUES('clan_battle_s_boss_fix_reward',NULL,'350');
INSERT INTO sqlite_stat1 VALUES('reward_collect_guide',NULL,'426');
INSERT INTO sqlite_stat1 VALUES('kaiser_add_times_data',NULL,'192');
INSERT INTO sqlite_stat1 VALUES('pct_reward','pct_reward_0_pct_point_type','15 5');
INSERT INTO sqlite_stat1 VALUES('uek_drama','uek_drama_0_drama_id','379 10');
INSERT INTO sqlite_stat1 VALUES('shiori_quest','shiori_quest_0_drop_reward_id','240 10');
INSERT INTO sqlite_stat1 VALUES('shiori_quest','shiori_quest_0_event_id','240 20');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_fix_reward',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_fix_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_setup',NULL,'383');
INSERT INTO sqlite_stat1 VALUES('event_navi_comment',NULL,'1077');
INSERT INTO sqlite_stat1 VALUES('cooperation_quest_data',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('chara_e_ticket_data','chara_e_ticket_data_0_jewel_store_id','2 1');
COMMIT;
