PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
ANALYZE "sqlite_master";
INSERT INTO sqlite_stat1 VALUES('event_gacha_data',NULL,'33');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz','hatsune_quiz_0_event_id','4 4');
INSERT INTO sqlite_stat1 VALUES('goldset_data_2',NULL,'70');
INSERT INTO sqlite_stat1 VALUES('event_wave_group_data',NULL,'4518');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest_area','hatsune_quest_area_0_event_id','76 3');
INSERT INTO sqlite_stat1 VALUES('goldset_data_teamlevel',NULL,'200');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_story_condition',NULL,'188');
INSERT INTO sqlite_stat1 VALUES('clan_invite_level_group',NULL,'31');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','hatsune_special_battle_0_event_id','45 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_battle','sqlite_autoindex_hatsune_special_battle_1','45 3 1');
INSERT INTO sqlite_stat1 VALUES('event_introduction',NULL,'34');
INSERT INTO sqlite_stat1 VALUES('stamp',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('dungeon_area_data',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('fke_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('event_boss_treasure_box',NULL,'114');
INSERT INTO sqlite_stat1 VALUES('grand_arena_max_season_rank_reward',NULL,'118');
INSERT INTO sqlite_stat1 VALUES('dear_setting',NULL,'7');
INSERT INTO sqlite_stat1 VALUES('arena_max_rank_reward',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('album_production_list','album_production_list_0_unit_id','904 9');
INSERT INTO sqlite_stat1 VALUES('still','still_0_story_id','621 2');
INSERT INTO sqlite_stat1 VALUES('fix_lineup_group_set','fix_lineup_group_set_0_team_level_from_1_team_level_to','22 3 2');
INSERT INTO sqlite_stat1 VALUES('fix_lineup_group_set','sqlite_autoindex_fix_lineup_group_set_1','22 4 1 1');
INSERT INTO sqlite_stat1 VALUES('sekai_top_data',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('room_release_data',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('pct_system_fruits',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('pct_system',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest_condition',NULL,'680');
INSERT INTO sqlite_stat1 VALUES('login_bonus_adv','login_bonus_adv_0_login_bonus_id','10 3');
INSERT INTO sqlite_stat1 VALUES('pct_combo_coefficient',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha_data',NULL,'24');
INSERT INTO sqlite_stat1 VALUES('actual_unit_background',NULL,'102');
INSERT INTO sqlite_stat1 VALUES('room_effect_reward_get','sqlite_autoindex_room_effect_reward_get_1','69 8 1');
INSERT INTO sqlite_stat1 VALUES('voice_group',NULL,'93');
INSERT INTO sqlite_stat1 VALUES('seasonpass_mission_data',NULL,'64');
INSERT INTO sqlite_stat1 VALUES('seasonpass_foundation',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('fke_happening_list',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('glossary_detail',NULL,'81');
INSERT INTO sqlite_stat1 VALUES('position_setting',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period','clan_battle_period_0_clan_battle_id','23 1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period','sqlite_autoindex_clan_battle_period_1','23 1 1');
INSERT INTO sqlite_stat1 VALUES('room_chat_scenario','room_chat_scenario_0_id','274 11');
INSERT INTO sqlite_stat1 VALUES('room_chat_scenario','sqlite_autoindex_room_chat_scenario_1','274 11 1');
INSERT INTO sqlite_stat1 VALUES('login_bonus_detail','login_bonus_detail_0_login_bonus_id_1_count','152 9 2');
INSERT INTO sqlite_stat1 VALUES('unit_status_coefficient',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('sekai_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('prizegacha_data',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('clan_battle_last_attack_reward',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('clan_battle_schedule',NULL,'23');
INSERT INTO sqlite_stat1 VALUES('unit_background',NULL,'113');
INSERT INTO sqlite_stat1 VALUES('kaiser_special_battle',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('hatsune_present','hatsune_present_0_event_id','4 1');
INSERT INTO sqlite_stat1 VALUES('clan_cost_group',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('navi_comment',NULL,'75');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_data','hatsune_diary_data_0_contents_type','17 9');
INSERT INTO sqlite_stat1 VALUES('grand_arena_daily_rank_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_effect',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('room_chat_info',NULL,'25');
INSERT INTO sqlite_stat1 VALUES('unit_skill_data',NULL,'691');
INSERT INTO sqlite_stat1 VALUES('srt_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('event_revival_wave_group_data',NULL,'4518');
INSERT INTO sqlite_stat1 VALUES('story_quest_data',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('seasonpass_mission_reward_data','seasonpass_mission_reward_data_0_mission_reward_id','18 2');
INSERT INTO sqlite_stat1 VALUES('voice_group_chara',NULL,'65');
INSERT INTO sqlite_stat1 VALUES('dear_story_detail','dear_story_detail_0_story_group_id_1_chara_index','172 25 10');
INSERT INTO sqlite_stat1 VALUES('clan_battle_s_boss_data',NULL,'120');
INSERT INTO sqlite_stat1 VALUES('clan_battle_2_map_data','clan_battle_2_map_data_0_clan_battle_id','79 4');
INSERT INTO sqlite_stat1 VALUES('story_data',NULL,'149');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_script','hatsune_diary_script_0_diary_id','427 31');
INSERT INTO sqlite_stat1 VALUES('gift_message',NULL,'84');
INSERT INTO sqlite_stat1 VALUES('skill_action',NULL,'3507');
INSERT INTO sqlite_stat1 VALUES('kaiser_extermination_reward',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('emblem_data',NULL,'410');
INSERT INTO sqlite_stat1 VALUES('vote_unit','sqlite_autoindex_vote_unit_1','55 55 1');
INSERT INTO sqlite_stat1 VALUES('pct_itempoint','pct_itempoint_0_item_id','3 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_setting',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quest','hatsune_quest_0_event_id','660 20');
INSERT INTO sqlite_stat1 VALUES('room_unit_comments','room_unit_comments_0_unit_id','3547 24');
INSERT INTO sqlite_stat1 VALUES('room_unit_comments','sqlite_autoindex_room_unit_comments_1','3547 24 8 2 1');
INSERT INTO sqlite_stat1 VALUES('tower_story_detail',NULL,'60');
INSERT INTO sqlite_stat1 VALUES('srt_score',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('hatsune_daily_mission_data',NULL,'67');
INSERT INTO sqlite_stat1 VALUES('login_bonus_message_data','login_bonus_message_data_0_login_bonus_id','118 40');
INSERT INTO sqlite_stat1 VALUES('rarity_6_quest_data','rarity_6_quest_data_0_rarity_6_quest_id','8 1');
INSERT INTO sqlite_stat1 VALUES('goldset_data',NULL,'70');
INSERT INTO sqlite_stat1 VALUES('sekai_add_times_data',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('clan_battle_s_map_data','clan_battle_s_map_data_0_clan_battle_id','78 4');
INSERT INTO sqlite_stat1 VALUES('unit_unique_equip',NULL,'71');
INSERT INTO sqlite_stat1 VALUES('story_detail',NULL,'948');
INSERT INTO sqlite_stat1 VALUES('content_map_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('odds_name_data',NULL,'81');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_boss_ticket_count',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_mode',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('gacha_data',NULL,'226');
INSERT INTO sqlite_stat1 VALUES('room_character_skin_color',NULL,'106');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','room_item_detail_0_lvup_trigger_type_2_1_lvup_trigger_id_2','487 487 487');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','room_item_detail_0_lvup_trigger_type_1_lvup_trigger_id','487 244 244');
INSERT INTO sqlite_stat1 VALUES('room_item_detail','sqlite_autoindex_room_item_detail_1','487 2 1');
INSERT INTO sqlite_stat1 VALUES('quest_defeat_notice',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('pct_evaluation',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('hatsune_multi_route_parameter','hatsune_multi_route_parameter_0_type','10 4');
INSERT INTO sqlite_stat1 VALUES('hatsune_multi_route_parameter','hatsune_multi_route_parameter_0_quest_id','10 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss_condition',NULL,'119');
INSERT INTO sqlite_stat1 VALUES('sekai_enemy_parameter',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period_rank_reward',NULL,'345');
INSERT INTO sqlite_stat1 VALUES('event_story_detail','event_story_detail_0_story_group_id','188 9');
INSERT INTO sqlite_stat1 VALUES('worldmap',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('training_quest_data',NULL,'16');
INSERT INTO sqlite_stat1 VALUES('unit_introduction','unit_introduction_0_gacha_id','62 1');
INSERT INTO sqlite_stat1 VALUES('quest_reward_data',NULL,'1499');
INSERT INTO sqlite_stat1 VALUES('quest_data',NULL,'560');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_reward_data','emblem_mission_reward_data_0_reward_id','498 2');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_reward_data','emblem_mission_reward_data_0_mission_reward_id','498 2');
INSERT INTO sqlite_stat1 VALUES('tower_quest_fix_reward_group',NULL,'413');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_mission_data',NULL,'107');
INSERT INTO sqlite_stat1 VALUES('sekai_unlock_story_condition',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('dungeon_quest_data',NULL,'37');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_reward_data','campaign_mission_reward_data_0_campaign_mission_reward_id','12 2');
INSERT INTO sqlite_stat1 VALUES('emblem_mission_data',NULL,'376');
INSERT INTO sqlite_stat1 VALUES('pct_gaming_motion',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('dear_reward','dear_reward_0_event_id_1_chara_index','90 13 5');
INSERT INTO sqlite_stat1 VALUES('hatsune_unlock_unit_condition',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('room_chat_formation',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_data','campaign_mission_data_0_campaign_id_1_type','16 16 8');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_data','campaign_mission_data_0_campaign_id','16 16');
INSERT INTO sqlite_stat1 VALUES('hatsune_relay_data',NULL,'48');
INSERT INTO sqlite_stat1 VALUES('album_voice_list','album_voice_list_0_unit_id','3182 37');
INSERT INTO sqlite_stat1 VALUES('season_pack','season_pack_0_mission_id','11 3');
INSERT INTO sqlite_stat1 VALUES('tower_area_data',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('event_boss_treasure_content',NULL,'546');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz_condition','hatsune_quiz_condition_0_event_id_1_quiz_id','6 6 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_mission_reward_data','hatsune_mission_reward_data_0_mission_reward_id','2046 2');
INSERT INTO sqlite_stat1 VALUES('sd_navi_comment',NULL,'7');
INSERT INTO sqlite_stat1 VALUES('experience_team',NULL,'155');
INSERT INTO sqlite_stat1 VALUES('arena_daily_rank_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_change',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('story_character_mask',NULL,'352');
INSERT INTO sqlite_stat1 VALUES('tips',NULL,'72');
INSERT INTO sqlite_stat1 VALUES('arcade_list',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('kaiser_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('tower_quest_data','tower_quest_data_0_floor_num','390 1');
INSERT INTO sqlite_stat1 VALUES('minigame','minigame_0_event_id','4 1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_period_lap_reward',NULL,'186');
INSERT INTO sqlite_stat1 VALUES('clan_battle_2_boss_data',NULL,'120');
INSERT INTO sqlite_stat1 VALUES('room_skin_color',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('resist_data',NULL,'32');
INSERT INTO sqlite_stat1 VALUES('hatsune_special_enemy',NULL,'39');
INSERT INTO sqlite_stat1 VALUES('hatsune_map',NULL,'14');
INSERT INTO sqlite_stat1 VALUES('room_item_announcement',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('enemy_m_parts',NULL,'28');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_reward',NULL,'20');
INSERT INTO sqlite_stat1 VALUES('experience_unit',NULL,'155');
INSERT INTO sqlite_stat1 VALUES('vote_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('event_story_data','event_story_data_0_value','23 1');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_schedule',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('equipment_craft',NULL,'236');
INSERT INTO sqlite_stat1 VALUES('hatsune_stationary_mission_data',NULL,'1043');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_material_id','56 4');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_unit_id_1_unlock_level','56 7 2');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','unlock_rarity_6_0_unit_id_1_slot_id','56 7 3');
INSERT INTO sqlite_stat1 VALUES('unlock_rarity_6','sqlite_autoindex_unlock_rarity_6_1','56 7 3 1');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_craft',NULL,'74');
INSERT INTO sqlite_stat1 VALUES('clan_battle_odds_data','clan_battle_odds_data_0_odds_group_id','22 5');
INSERT INTO sqlite_stat1 VALUES('clan_battle_odds_data','sqlite_autoindex_clan_battle_odds_data_1','22 5 1 1');
INSERT INTO sqlite_stat1 VALUES('unit_data',NULL,'147');
INSERT INTO sqlite_stat1 VALUES('ailment_data',NULL,'29');
INSERT INTO sqlite_stat1 VALUES('kmk_reward',NULL,'15');
INSERT INTO sqlite_stat1 VALUES('pct_tap_speed',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('skip_monster_data',NULL,'1264');
INSERT INTO sqlite_stat1 VALUES('quest_condition_data',NULL,'561');
INSERT INTO sqlite_stat1 VALUES('enemy_enable_voice',NULL,'45');
INSERT INTO sqlite_stat1 VALUES('clanprofile_content',NULL,'29');
INSERT INTO sqlite_stat1 VALUES('enemy_reward_data',NULL,'2042');
INSERT INTO sqlite_stat1 VALUES('room_item',NULL,'423');
INSERT INTO sqlite_stat1 VALUES('skill_cost',NULL,'157');
INSERT INTO sqlite_stat1 VALUES('notif_data','notif_data_0_unit_id','636 6');
INSERT INTO sqlite_stat1 VALUES('notif_data','sqlite_autoindex_notif_data_1','636 6 1');
INSERT INTO sqlite_stat1 VALUES('arcade_story_list',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('unlock_skill_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('myprofile_content',NULL,'19');
INSERT INTO sqlite_stat1 VALUES('kaiser_quest_data',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('vote_info','sqlite_autoindex_vote_info_1','3 3 1');
INSERT INTO sqlite_stat1 VALUES('tower_schedule','tower_schedule_0_opening_story_id','18 1');
INSERT INTO sqlite_stat1 VALUES('event_enemy_reward_group',NULL,'137');
INSERT INTO sqlite_stat1 VALUES('hatsune_diary_letter_script','hatsune_diary_letter_script_0_diary_id','151 51');
INSERT INTO sqlite_stat1 VALUES('hatsune_description','hatsune_description_0_event_id_1_type','179 6 3');
INSERT INTO sqlite_stat1 VALUES('campaign_freegacha',NULL,'8');
INSERT INTO sqlite_stat1 VALUES('arena_max_season_rank_reward',NULL,'118');
INSERT INTO sqlite_stat1 VALUES('unit_promotion_status','sqlite_autoindex_unit_promotion_status_1','1740 15 1');
INSERT INTO sqlite_stat1 VALUES('unit_comments','unit_comments_0_unit_id_1_use_type','1336 6 4');
INSERT INTO sqlite_stat1 VALUES('unit_comments','unit_comments_0_unit_id','1336 6');
INSERT INTO sqlite_stat1 VALUES('dear_story_data','dear_story_data_0_value','7 1');
INSERT INTO sqlite_stat1 VALUES('quest_area_data',NULL,'71');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_data',NULL,'74');
INSERT INTO sqlite_stat1 VALUES('music_list',NULL,'114');
INSERT INTO sqlite_stat1 VALUES('event_top_adv','event_top_adv_0_event_id_1_type','289 11 3');
INSERT INTO sqlite_stat1 VALUES('hatsune_bg_change_data','hatsune_bg_change_data_0_target_type_1_area_id','10 5 2');
INSERT INTO sqlite_stat1 VALUES('gacha_exchange_lineup',NULL,'104');
INSERT INTO sqlite_stat1 VALUES('campaign_schedule',NULL,'381');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','unit_rarity_0_unit_material_id','648 6');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','unit_rarity_0_unit_id','648 6');
INSERT INTO sqlite_stat1 VALUES('unit_rarity','sqlite_autoindex_unit_rarity_1','648 6 1');
INSERT INTO sqlite_stat1 VALUES('enemy_parameter',NULL,'5180');
INSERT INTO sqlite_stat1 VALUES('tower_enemy_parameter',NULL,'2073');
INSERT INTO sqlite_stat1 VALUES('content_release_data',NULL,'29');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_damage_rank_reward',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('grand_arena_max_rank_reward',NULL,'79');
INSERT INTO sqlite_stat1 VALUES('combined_result_motion',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('unit_profile',NULL,'114');
INSERT INTO sqlite_stat1 VALUES('specialfes_banner',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('tower_wave_group_data',NULL,'423');
INSERT INTO sqlite_stat1 VALUES('login_bonus_data',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('unit_attack_pattern',NULL,'852');
INSERT INTO sqlite_stat1 VALUES('chara_story_status',NULL,'592');
INSERT INTO sqlite_stat1 VALUES('visual_customize',NULL,'3');
INSERT INTO sqlite_stat1 VALUES('music_content',NULL,'117');
INSERT INTO sqlite_stat1 VALUES('tower_ex_quest_data','tower_ex_quest_data_0_floor_num','18 1');
INSERT INTO sqlite_stat1 VALUES('event_enemy_parameter',NULL,'3764');
INSERT INTO sqlite_stat1 VALUES('room_emotion_icon',NULL,'18');
INSERT INTO sqlite_stat1 VALUES('hatsune_emblem_mission',NULL,'45');
INSERT INTO sqlite_stat1 VALUES('sekai_top_story_data',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('clan_grade',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('bg_data','sqlite_autoindex_bg_data_1','118 1');
INSERT INTO sqlite_stat1 VALUES('skill_data',NULL,'1571');
INSERT INTO sqlite_stat1 VALUES('love_chara',NULL,'12');
INSERT INTO sqlite_stat1 VALUES('hatsune_boss','hatsune_boss_0_event_id_1_difficulty','119 4 1');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_damage_rank','clan_battle_boss_damage_rank_0_damage_rank_id','160 4');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_damage_rank','sqlite_autoindex_clan_battle_boss_damage_rank_1','160 4 1 1');
INSERT INTO sqlite_stat1 VALUES('wave_group_data',NULL,'2387');
INSERT INTO sqlite_stat1 VALUES('campaign_mission_category','campaign_mission_category_0_campaign_id_1_type','2 2 1');
INSERT INTO sqlite_stat1 VALUES('equipment_enhance_rate',NULL,'273');
INSERT INTO sqlite_stat1 VALUES('kaiser_restriction_group','kaiser_restriction_group_0_restriction_group_id','102 21');
INSERT INTO sqlite_stat1 VALUES('kaiser_restriction_group','sqlite_autoindex_kaiser_restriction_group_1','102 21 1');
INSERT INTO sqlite_stat1 VALUES('srt_top_talk','srt_top_talk_0_talk_id','45 2');
INSERT INTO sqlite_stat1 VALUES('srt_panel','srt_panel_0_panel_id','438 4');
INSERT INTO sqlite_stat1 VALUES('skip_boss_data',NULL,'68');
INSERT INTO sqlite_stat1 VALUES('global_data','sqlite_autoindex_global_data_1','2 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_quiz_reward',NULL,'4');
INSERT INTO sqlite_stat1 VALUES('tower_story_data',NULL,'10');
INSERT INTO sqlite_stat1 VALUES('equipment_enhance_data','sqlite_autoindex_equipment_enhance_data_1','14 4 1');
INSERT INTO sqlite_stat1 VALUES('pct_result','pct_result_0_character_id','4 2');
INSERT INTO sqlite_stat1 VALUES('shop_static_price_group',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('event_bg_data',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('profile_frame',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('seasonpass_level_reward',NULL,'100');
INSERT INTO sqlite_stat1 VALUES('grand_arena_defence_reward',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('chara_fortune_schedule',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('unit_mypage_pos',NULL,'36');
INSERT INTO sqlite_stat1 VALUES('unlock_unit_condition',NULL,'107');
INSERT INTO sqlite_stat1 VALUES('daily_mission_data',NULL,'374');
INSERT INTO sqlite_stat1 VALUES('equipment_donation',NULL,'9');
INSERT INTO sqlite_stat1 VALUES('equipment_data',NULL,'509');
INSERT INTO sqlite_stat1 VALUES('hatsune_map_event','hatsune_map_event_0_target_event_id','91 11');
INSERT INTO sqlite_stat1 VALUES('movie',NULL,'184');
INSERT INTO sqlite_stat1 VALUES('chara_identity',NULL,'110');
INSERT INTO sqlite_stat1 VALUES('character_love_rankup_text',NULL,'42');
INSERT INTO sqlite_stat1 VALUES('srt_action','sqlite_autoindex_srt_action_1','41 1');
INSERT INTO sqlite_stat1 VALUES('arena_defence_reward',NULL,'1');
INSERT INTO sqlite_stat1 VALUES('banner',NULL,'90');
INSERT INTO sqlite_stat1 VALUES('stationary_mission_data',NULL,'828');
INSERT INTO sqlite_stat1 VALUES('dear_chara','dear_chara_0_event_id','18 3');
INSERT INTO sqlite_stat1 VALUES('dear_chara','sqlite_autoindex_dear_chara_1','18 3 1');
INSERT INTO sqlite_stat1 VALUES('unit_enemy_data',NULL,'599');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_enhance_data','sqlite_autoindex_unique_equipment_enhance_data_1','159 159 1');
INSERT INTO sqlite_stat1 VALUES('kmk_navi_comment',NULL,'11');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_enhance_rate',NULL,'74');
INSERT INTO sqlite_stat1 VALUES('hatsune_item',NULL,'34');
INSERT INTO sqlite_stat1 VALUES('unit_motion_list',NULL,'108');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_rankup','unique_equipment_rankup_0_equip_id','592 8');
INSERT INTO sqlite_stat1 VALUES('unique_equipment_rankup','sqlite_autoindex_unique_equipment_rankup_1','592 8 1');
INSERT INTO sqlite_stat1 VALUES('hatsune_emblem_mission_reward','hatsune_emblem_mission_reward_0_reward_id','86 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_emblem_mission_reward','hatsune_emblem_mission_reward_0_mission_reward_id','86 2');
INSERT INTO sqlite_stat1 VALUES('hatsune_schedule','hatsune_schedule_0_series_event_id','34 34');
INSERT INTO sqlite_stat1 VALUES('room_character_personality',NULL,'109');
INSERT INTO sqlite_stat1 VALUES('unit_promotion','unit_promotion_0_unit_id','2116 16');
INSERT INTO sqlite_stat1 VALUES('unit_promotion','sqlite_autoindex_unit_promotion_1','2116 16 1');
INSERT INTO sqlite_stat1 VALUES('item_data',NULL,'217');
INSERT INTO sqlite_stat1 VALUES('clan_battle_s_boss_fix_reward',NULL,'126');
INSERT INTO sqlite_stat1 VALUES('reward_collect_guide',NULL,'426');
INSERT INTO sqlite_stat1 VALUES('kaiser_add_times_data',NULL,'192');
INSERT INTO sqlite_stat1 VALUES('pct_reward','pct_reward_0_pct_point_type','1 1');
INSERT INTO sqlite_stat1 VALUES('sekai_boss_fix_reward',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('clan_battle_boss_fix_reward',NULL,'40');
INSERT INTO sqlite_stat1 VALUES('room_setup',NULL,'350');
INSERT INTO sqlite_stat1 VALUES('event_navi_comment',NULL,'21');
INSERT INTO sqlite_stat1 VALUES('cooperation_quest_data',NULL,'6');
INSERT INTO sqlite_stat1 VALUES('chara_e_ticket_data','chara_e_ticket_data_0_jewel_store_id','1 1');
INSERT INTO sqlite_stat1 VALUES('tower_cloister_quest_data',NULL,'5');
INSERT INTO sqlite_stat1 VALUES('hatsune_bg_change',NULL,'2');
INSERT INTO sqlite_stat1 VALUES('guild',NULL,'17');
INSERT INTO sqlite_stat1 VALUES('mission_reward_data','mission_reward_data_0_mission_reward_id','346 2');
COMMIT;
