PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS 'srt_action' ('action_name' TEXT NOT NULL, 'inori_action' TEXT NOT NULL, 'dragon_action' TEXT NOT NULL, 'kaya_action' TEXT NOT NULL, 'homare_action' TEXT NOT NULL, 'talk_text_type' INTEGER NOT NULL, 'talk_text' TEXT NOT NULL, 'voice_list' TEXT NOT NULL, PRIMARY KEY('action_name'));
INSERT INTO srt_action VALUES('GAME_START','srt_inori_idle','srt_dragon_in,srt_dragon_idle','srt_kaya_idle','',0,'','start_000-start_001,start_002/start_003-boss_emote_064-start_004');
INSERT INTO srt_action VALUES('ENEMY_FIRST','srt_inori_idle','srt_dragon_idle','srt_kaya_idle','',2,'先从我开始吧！','');
INSERT INTO srt_action VALUES('ENEMY_TURN1','srt_inori_idle','srt_dragon_idle','srt_kaya_waiting','',2,'“{0}”吗\n以“{1}”开头的是……','');
INSERT INTO srt_action VALUES('ENEMY_TURN2','srt_inori_idle','srt_dragon_idle','srt_kaya_waiting','',2,'“{0}”吗\n嗯，“{1}”开头的词语啊……','');
INSERT INTO srt_action VALUES('ENEMY_TURN3','srt_inori_idle','srt_dragon_idle','srt_kaya_waiting','',2,'“{0}”吗，\n好，接下来就是“{1}”了吧','');
INSERT INTO srt_action VALUES('ENEMY_HELP','','','srt_kaya_help','srt_homare_help',0,'','sugoyomi_damage_059,sugoyomi_damage_060,sugoyomi_damage_061,sugoyomi_damage_062,sugoyomi_damage_063');
INSERT INTO srt_action VALUES('ENEMY_FLASH','','','srt_kaya_flash','',0,'','');
INSERT INTO srt_action VALUES('ENEMY_SELECT1','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'是“{0}”吧！','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO srt_action VALUES('ENEMY_SELECT2','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'是“{0}”！','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO srt_action VALUES('ENEMY_SELECT3','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'是“{0}”啊！','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO srt_action VALUES('ENEMY_SELECT_GREAT1','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'“{0}”怎么样！','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO srt_action VALUES('ENEMY_SELECT_GREAT2','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'嘿哼！是“{0}”！','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO srt_action VALUES('ENEMY_SELECT_WAIT','','','','',-1,'','');
INSERT INTO srt_action VALUES('ENEMY_SELECT_N','','','srt_kaya_shock','',1,'嘉夜夜，你的结尾带上“嗯”了啊……','out_071');
INSERT INTO srt_action VALUES('PLAYER_TURN1','srt_inori_thinking','srt_dragon_thinking','srt_kaya_waiting','',1,'“{0}”吗，\n那接下来就是以“{1}”开头的词语了','');
INSERT INTO srt_action VALUES('PLAYER_TURN2','srt_inori_thinking','srt_dragon_thinking','srt_kaya_waiting','',1,'“{0}”吗\n嗯，以“{1}”开始的词语……','');
INSERT INTO srt_action VALUES('PLAYER_TURN3','srt_inori_thinking','srt_dragon_thinking','srt_kaya_waiting','',1,'原来如此，以“{0}”开头啊\n嗯嗯，以“{1}”开头的词语……','');
INSERT INTO srt_action VALUES('PLAYER_CUTIN_GREAT','','','','',1,'','sugoyomi_cutin_049,sugoyomi_cutin_051,sugoyomi_cutin_053');
INSERT INTO srt_action VALUES('PLAYER_CUTIN_PRICONNE','','','','',1,'','sugoyomi_cutin_050,sugoyomi_cutin_052');
INSERT INTO srt_action VALUES('PLAYER_SELECT1','srt_inori_select_1,srt_inori_idle','srt_dragon_select_1,srt_dragon_idle','srt_kaya_react_1,srt_kaya_waiting','',1,'“{0}”！','correct_028-correct_029,correct_032/correct_033-boss_emote_067-correct_034,correct_037-correct_038');
INSERT INTO srt_action VALUES('PLAYER_SELECT2','srt_inori_select_2,srt_inori_idle','srt_dragon_select_2,srt_dragon_idle','srt_kaya_react_2,srt_kaya_waiting','',1,'是“{0}”对吧！','correct_030-correct_031,correct_035-correct_036');
INSERT INTO srt_action VALUES('PLAYER_SELECT_GREAT1','srt_inori_select_1,srt_inori_idle','srt_dragon_select_1,srt_dragon_idle','srt_kaya_react_1,srt_kaya_waiting','',1,'“{0}”怎么样！','correct_028-correct_029,correct_032/correct_033-boss_emote_067-correct_034,correct_037-correct_038');
INSERT INTO srt_action VALUES('PLAYER_SELECT_GREAT2','srt_inori_select_2,srt_inori_idle','srt_dragon_select_2,srt_dragon_idle','srt_kaya_react_2,srt_kaya_waiting','',1,'哼哼♪是“{0}”！','correct_030-correct_031,correct_035-correct_036');
INSERT INTO srt_action VALUES('PLAYER_SELECT_PRECONNE1','srt_inori_select_1,srt_inori_idle','srt_dragon_select_1,srt_dragon_idle','srt_kaya_react_1,srt_kaya_waiting','',1,'呵呵呵，关键词是\n“{0}”！','correct_028-correct_029,correct_032/correct_033-boss_emote_067-correct_034,correct_037-correct_038');
INSERT INTO srt_action VALUES('PLAYER_SELECT_PRECONNE2','srt_inori_select_2,srt_inori_idle','srt_dragon_select_2,srt_dragon_idle','srt_kaya_react_2,srt_kaya_waiting','',1,'我想到了！\n是“{0}”对吧！','correct_030-correct_031,correct_035-correct_036');
INSERT INTO srt_action VALUES('PLAYER_SELECT_WAIT','','','','',-1,'','');
INSERT INTO srt_action VALUES('PLAYER_MISS','srt_inori_miss,srt_inori_thinking','srt_dragon_miss,srt_dragon_thinking','srt_kaya_react_3,srt_kaya_waiting','',1,'啊呜！错、错了……','mistake_039-mistake_040,mistake_041-mistake_042,mistake_043-mistake_044,mistake_045-mistake_046');
INSERT INTO srt_action VALUES('PLAYER_SELECT_N','srt_inori_shock','','srt_kaya_react_4','',2,'喂喂，结尾带上“嗯”了啊……','out_070');
INSERT INTO srt_action VALUES('INFEVER','srt_inori_thinking','srt_dragon_thinking','srt_kaya_infever','',1,'要继续咯！','rush');
INSERT INTO srt_action VALUES('FEVER_SELECT1','srt_inori_select_1','srt_dragon_select_1','','',1,'“{0}”！','correct_028-correct_029,correct_037-correct_038');
INSERT INTO srt_action VALUES('FEVER_SELECT2','srt_inori_select_2','srt_dragon_select_2','','',1,'是“{0}”对吧！','correct_030-correct_031,correct_035-correct_036');
INSERT INTO srt_action VALUES('FEVER_MISS','srt_inori_miss','srt_dragon_miss','','',1,'啊呜！错、错了……','mistake_039-mistake_040,mistake_041-mistake_042,mistake_043-mistake_044,mistake_045-mistake_046,mistake_047-mistake_048');
INSERT INTO srt_action VALUES('FEVER_DAMAGE','srt_inori_fever_attack','srt_dragon_fever_attack','srt_kaya_fever_damage','',1,'做好觉悟吧！','rush_attack');
INSERT INTO srt_action VALUES('WIN_HP','srt_inori_win_1','srt_dragon_win','srt_kaya_lose','',1,'是我们赢了哦！','win_005-win_006,win_012-win_013');
INSERT INTO srt_action VALUES('WIN_N','srt_inori_win_1','srt_dragon_win','','',1,'是我们赢了哦！','win_005-win_006,win_012-win_013');
INSERT INTO srt_action VALUES('LOSE_MISS','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'啊呜呜……是我输了……','lose_017,lose_019,lose_023');
INSERT INTO srt_action VALUES('LOSE_N','','srt_dragon_miss','','',1,'啊呜呜……是我输了……','lose_017,lose_019,lose_023');
INSERT INTO srt_action VALUES('TIMEUP','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'时、时间到了吗！？是我大意了…… ','lose_025/lose_026-boss_emote_068,lose_021');
INSERT INTO srt_action VALUES('LOSE_MISS2','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'啊呜呜……我输了……\n已经出现过“{0}”了……','lose_017,lose_019,lose_023');
INSERT INTO srt_action VALUES('LOSE_N2','','srt_dragon_miss','','',1,'啊呜呜……我输了……\n已经出现过“{0}”了……','lose_017,lose_019,lose_023');
INSERT INTO srt_action VALUES('TIMEUP2','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'时、时间到了吗！？我太大意了…… \n已经出现过“{0}”了……','lose_025/lose_026-boss_emote_068,lose_021');
COMMIT;
